// @generated by `cargo xtask catalogue` from `catalogue.bnf`. DO NOT EDIT.
//
// The `io.` constructors that read through a native DuckDB table function.
// A materialised row (`io.rdf`) has no reader to DESCRIBE through and is
// deliberately absent — `packages/executor` gets the list that includes it.
//
// Edit `catalogue.bnf` and re-run `cargo xtask catalogue`.

/** The DuckDB table function each constructor reads through. */
export const NATIVE_READERS = {
  csv: "read_csv_auto",
  json: "read_json_auto",
  parquet: "read_parquet",
} as const;

/** The constructors above, in catalogue order — the alternation's corpus. */
export const NATIVE_ROWS = ["csv", "json", "parquet"] as const;

/** One `io.` constructor that reads through a native reader. */
export type NativeRow = (typeof NATIVE_ROWS)[number];
