// @generated by `cargo xtask catalogue` from `catalogue.bnf`. DO NOT EDIT.
//
// The `io.` constructors that read through a native DuckDB table function,
// and what the DESCRIBE answers means. A materialised row (`io.rdf`) has no
// reader to DESCRIBE through and is deliberately absent.
//
// Edit `catalogue.bnf` and re-run `cargo xtask catalogue`.

import type { Primitive } from "@fossil-lang/types";

/** The DuckDB table function each constructor reads through. */
export const NATIVE_READERS = {
  csv: "read_csv_auto",
  json: "read_json_auto",
  parquet: "read_parquet",
} as const;

/** The constructors above, in catalogue order. */
export const NATIVE_ROWS = ["csv", "json", "parquet"] as const;

/** One `io.` constructor that reads through a native reader. */
export type NativeRow = (typeof NATIVE_ROWS)[number];

/** The DuckDB named parameter each constructor's reader option is spelled with. */
export const NATIVE_OPTIONS: Partial<Record<NativeRow, string>> = {
  csv: "delim",
};

/** The `Primitive` a DuckDB column type means: case-blind, the first `duckdb` line
 *  of `catalogue.bnf` that matches. */
export function duckdbPrimitive(t: string): Primitive {
  const upper = t.trim().toUpperCase();
  if (upper === "INTEGER" || upper === "BIGINT" || upper === "INT" || upper === "SMALLINT" || upper === "TINYINT" || upper === "HUGEINT") return "integer";
  if (upper === "DOUBLE" || upper === "FLOAT" || upper === "REAL" || upper.startsWith("DECIMAL")) return "float";
  if (upper === "BOOLEAN" || upper === "BOOL") return "bool";
  if (upper === "DATE") return "date";
  if (upper.startsWith("TIMESTAMP") || upper === "DATETIME") return "date_time";
  if (upper.startsWith("TIME")) return "time";
  return "string";
}
