// @generated by `cargo xtask catalogue` from `catalogue.bnf`. DO NOT EDIT.
//
// The `io.` constructors that read through a native DuckDB table function.
// A materialised row (`io.rdf`) has no reader to DESCRIBE through and is
// deliberately absent — `packages/executor` gets the list that includes it.
//
// Edit `catalogue.bnf` and re-run `cargo xtask catalogue`.

/** The DuckDB table function each constructor reads through. */
export const NATIVE_READERS = {
  csv: "read_csv_auto",
  json: "read_json_auto",
  parquet: "read_parquet",
} as const;

/** The constructors above, in catalogue order — the alternation's corpus. */
export const NATIVE_ROWS = ["csv", "json", "parquet"] as const;

/** One `io.` constructor that reads through a native reader. */
export type NativeRow = (typeof NATIVE_ROWS)[number];

/**
 * The reader options each constructor takes — the named, optional positions
 * of its signature. Empty for a row that takes none.
 *
 * The counterpart of `fossil_base::Provider::options`, from the same rows.
 * The browser scrapes a source binding for these and the native host does
 * too, so the word a program writes is the catalogue's on both sides; what
 * each one sends to its own DuckDB is its own.
 */
export const READER_OPTIONS = {
  csv: ["delimiter"],
  json: [],
  parquet: [],
} as const satisfies Record<NativeRow, readonly string[]>;
