//! @generated by `cargo xtask corpus` from `corpus.bnf`. DO NOT EDIT.
//!
//! The columns the writer emits, and what each one IS. `corpus.bnf` carries the
//! rows and the argument; this is the Rust projection of them.
//!
//! **Read a set by the ROLES it means, not by a name you remember.** The two
//! consumers that used to carry hand-written lists meant different things by
//! "the writer's columns" and nothing said so — see `corpus.bnf`.

/// What a column IS — never what a reader does with it.
///
/// A reader that used to carry a list now names the roles it means.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub enum ColumnRole {
    /// The row's rank in the ordering, which a re-layout renumbers.
    Address,
    /// What a bookmark keys on, and what survives a rebuild.
    Identity,
    /// One axis of the plane.
    Coordinate,
    /// An ordinal the writer computed, for a reader to colour by.
    Categorical,
    /// One end of a relation, in the aligned type's `dense_id` space.
    Endpoint,
}

/// One column the writer emits.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct WriterColumn {
    /// The column name, as it appears in the Parquet schema.
    pub name: &'static str,
    /// The `GraphAr` spelling of its type, which is what the manifest writes.
    pub data_type: &'static str,
    pub role: ColumnRole,
    /// Whether the manifest's `properties:` also declares it.
    pub declared: bool,
}

/// Every column of a vertex payload row, in writer order.
pub const PAYLOAD_COLUMNS: &[WriterColumn] = &[
    WriterColumn {
        name: "dense_id",
        data_type: "uint32",
        role: ColumnRole::Address,
        declared: false,
    },
    WriterColumn {
        name: "subject",
        data_type: "string",
        role: ColumnRole::Identity,
        declared: true,
    },
    WriterColumn {
        name: "x",
        data_type: "float32",
        role: ColumnRole::Coordinate,
        declared: false,
    },
    WriterColumn {
        name: "y",
        data_type: "float32",
        role: ColumnRole::Coordinate,
        declared: false,
    },
    WriterColumn {
        name: "cluster_id",
        data_type: "uint32",
        role: ColumnRole::Categorical,
        declared: false,
    },
];

/// The names of a vertex payload row, in writer order.
pub const PAYLOAD_NAMES: &[&str] = &["dense_id", "subject", "x", "y", "cluster_id"];

/// The address column(s) of a vertex payload row — the row's rank in the ordering, which a re-layout renumbers.
pub const PAYLOAD_ADDRESS: &[&str] = &["dense_id"];

/// The identity column(s) of a vertex payload row — what a bookmark keys on, and what survives a rebuild.
pub const PAYLOAD_IDENTITY: &[&str] = &["subject"];

/// The coordinate column(s) of a vertex payload row — one axis of the plane.
pub const PAYLOAD_COORDINATES: &[&str] = &["x", "y"];

/// The categorical column(s) of a vertex payload row — an ordinal the writer computed, for a reader to colour by.
pub const PAYLOAD_CATEGORICAL: &[&str] = &["cluster_id"];

/// Every column of an adjacency row, in either orientation, in writer order.
pub const ADJACENCY_COLUMNS: &[WriterColumn] = &[
    WriterColumn {
        name: "src_dense",
        data_type: "uint32",
        role: ColumnRole::Endpoint,
        declared: false,
    },
    WriterColumn {
        name: "dst_dense",
        data_type: "uint32",
        role: ColumnRole::Endpoint,
        declared: false,
    },
];

/// The names of an adjacency row, in either orientation, in writer order.
pub const ADJACENCY_NAMES: &[&str] = &["src_dense", "dst_dense"];

/// The endpoint column(s) of an adjacency row, in either orientation — one end of a relation, in the aligned type's `dense_id` space.
pub const ADJACENCY_ENDPOINTS: &[&str] = &["src_dense", "dst_dense"];

/// The payload columns the manifest's `properties:` also declares.
///
/// One of five, and that asymmetry is the whole of the manifest-versus-bytes
/// difference a reader has to know about.
pub const PAYLOAD_DECLARED: &[&str] = &["subject"];

/// The endpoint column a `src`-aligned orientation is tiled by.
pub const ALIGNED_SRC: &str = "src_dense";

/// The endpoint column a `dst`-aligned orientation is tiled by.
pub const ALIGNED_DST: &str = "dst_dense";
