//! @generated by `cargo xtask corpus` from `corpus.bnf`. DO NOT EDIT.
//!
//! The columns the writer emits, and what each one IS. `corpus.bnf` carries the
//! rows and the argument; this is the Rust projection of them.
//!
//! **Read a set by the ROLES it means, not by a name you remember.** The two
//! consumers that used to carry hand-written lists meant different things by
//! "the writer's columns" and nothing said so — see `corpus.bnf`.

/// What a column IS — never what a reader does with it.
///
/// A reader that used to carry a list now names the roles it means.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub enum ColumnRole {
    /// The row's rank in the ordering, which a re-layout renumbers.
    Address,
    /// What a bookmark keys on, and what survives a rebuild.
    Identity,
    /// One axis of the plane.
    Coordinate,
    /// An ordinal the writer computed, for a reader to colour by.
    Categorical,
    /// One end of a relation, in the aligned type's `dense_id` space.
    Endpoint,
    /// How many rows of the level below this one summarises.
    Tally,
    /// A summed edge weight.
    Weight,
    /// The majority value of a categorical over the rows summarised.
    Mode,
    /// What fraction of the rows summarised carry the mode.
    Purity,
    /// One end of a quotient edge, in its own rung's cell space.
    Incident,
}

/// One column the writer emits.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct WriterColumn {
    /// The column name, as it appears in the Parquet schema.
    pub name: &'static str,
    /// The `GraphAr` spelling of its type, which is what the manifest writes.
    pub data_type: &'static str,
    pub role: ColumnRole,
    /// Whether the manifest's `properties:` also declares it.
    pub declared: bool,
}

/// Every column of a vertex payload row, in writer order.
pub const PAYLOAD_COLUMNS: &[WriterColumn] = &[
    WriterColumn {
        name: "dense_id",
        data_type: "uint32",
        role: ColumnRole::Address,
        declared: false,
    },
    WriterColumn {
        name: "subject",
        data_type: "string",
        role: ColumnRole::Identity,
        declared: true,
    },
    WriterColumn {
        name: "x",
        data_type: "float",
        role: ColumnRole::Coordinate,
        declared: false,
    },
    WriterColumn {
        name: "y",
        data_type: "float",
        role: ColumnRole::Coordinate,
        declared: false,
    },
    WriterColumn {
        name: "cluster_id",
        data_type: "uint32",
        role: ColumnRole::Categorical,
        declared: false,
    },
];

/// The names of a vertex payload row, in writer order.
pub const PAYLOAD_NAMES: &[&str] = &["dense_id", "subject", "x", "y", "cluster_id"];

/// The address column(s) of a vertex payload row — the row's rank in the ordering, which a re-layout renumbers.
pub const PAYLOAD_ADDRESS: &[&str] = &["dense_id"];

/// The identity column(s) of a vertex payload row — what a bookmark keys on, and what survives a rebuild.
pub const PAYLOAD_IDENTITY: &[&str] = &["subject"];

/// The coordinate column(s) of a vertex payload row — one axis of the plane.
pub const PAYLOAD_COORDINATES: &[&str] = &["x", "y"];

/// The categorical column(s) of a vertex payload row — an ordinal the writer computed, for a reader to colour by.
pub const PAYLOAD_CATEGORICAL: &[&str] = &["cluster_id"];

/// Every column of an adjacency row, in either orientation, in writer order.
pub const ADJACENCY_COLUMNS: &[WriterColumn] = &[
    WriterColumn {
        name: "src_dense",
        data_type: "uint32",
        role: ColumnRole::Endpoint,
        declared: false,
    },
    WriterColumn {
        name: "dst_dense",
        data_type: "uint32",
        role: ColumnRole::Endpoint,
        declared: false,
    },
];

/// The names of an adjacency row, in either orientation, in writer order.
pub const ADJACENCY_NAMES: &[&str] = &["src_dense", "dst_dense"];

/// The endpoint column(s) of an adjacency row, in either orientation — one end of a relation, in the aligned type's `dense_id` space.
pub const ADJACENCY_ENDPOINTS: &[&str] = &["src_dense", "dst_dense"];

/// Every column of a cell row of one rung of the pyramid, in writer order.
pub const CELL_COLUMNS: &[WriterColumn] = &[
    WriterColumn {
        name: "cell_id",
        data_type: "uint32",
        role: ColumnRole::Address,
        declared: false,
    },
    WriterColumn {
        name: "x",
        data_type: "float",
        role: ColumnRole::Coordinate,
        declared: false,
    },
    WriterColumn {
        name: "y",
        data_type: "float",
        role: ColumnRole::Coordinate,
        declared: false,
    },
    WriterColumn {
        name: "count",
        data_type: "uint32",
        role: ColumnRole::Tally,
        declared: false,
    },
    WriterColumn {
        name: "internal",
        data_type: "uint64",
        role: ColumnRole::Weight,
        declared: false,
    },
    WriterColumn {
        name: "mode",
        data_type: "uint32",
        role: ColumnRole::Mode,
        declared: false,
    },
    WriterColumn {
        name: "purity",
        data_type: "float",
        role: ColumnRole::Purity,
        declared: false,
    },
];

/// The names of a cell row of one rung of the pyramid, in writer order.
pub const CELL_NAMES: &[&str] = &["cell_id", "x", "y", "count", "internal", "mode", "purity"];

/// The address column(s) of a cell row of one rung of the pyramid — the row's rank in the ordering, which a re-layout renumbers.
pub const CELL_ADDRESS: &[&str] = &["cell_id"];

/// The coordinate column(s) of a cell row of one rung of the pyramid — one axis of the plane.
pub const CELL_COORDINATES: &[&str] = &["x", "y"];

/// The tally column(s) of a cell row of one rung of the pyramid — how many rows of the level below this one summarises.
pub const CELL_TALLY: &[&str] = &["count"];

/// The weight column(s) of a cell row of one rung of the pyramid — a summed edge weight.
pub const CELL_WEIGHT: &[&str] = &["internal"];

/// The mode column(s) of a cell row of one rung of the pyramid — the majority value of a categorical over the rows summarised.
pub const CELL_MODE: &[&str] = &["mode"];

/// The purity column(s) of a cell row of one rung of the pyramid — what fraction of the rows summarised carry the mode.
pub const CELL_PURITY: &[&str] = &["purity"];

/// Every column of a quotient edge between two cells of one rung, in writer order.
pub const QUOTIENT_COLUMNS: &[WriterColumn] = &[
    WriterColumn {
        name: "src_cell",
        data_type: "uint32",
        role: ColumnRole::Incident,
        declared: false,
    },
    WriterColumn {
        name: "dst_cell",
        data_type: "uint32",
        role: ColumnRole::Incident,
        declared: false,
    },
    WriterColumn {
        name: "weight",
        data_type: "uint64",
        role: ColumnRole::Weight,
        declared: false,
    },
];

/// The names of a quotient edge between two cells of one rung, in writer order.
pub const QUOTIENT_NAMES: &[&str] = &["src_cell", "dst_cell", "weight"];

/// The weight column(s) of a quotient edge between two cells of one rung — a summed edge weight.
pub const QUOTIENT_WEIGHT: &[&str] = &["weight"];

/// The incident column(s) of a quotient edge between two cells of one rung — one end of a quotient edge, in its own rung's cell space.
pub const QUOTIENT_INCIDENTS: &[&str] = &["src_cell", "dst_cell"];

/// The payload columns the manifest's `properties:` also declares.
///
/// One of five, and that asymmetry is the whole of the manifest-versus-bytes
/// difference a reader has to know about.
pub const PAYLOAD_DECLARED: &[&str] = &["subject"];

/// The endpoint column a `src`-aligned orientation is tiled by.
pub const ALIGNED_SRC: &str = "src_dense";

/// The endpoint column a `dst`-aligned orientation is tiled by.
pub const ALIGNED_DST: &str = "dst_dense";
