//! @generated by `cargo xtask corpus` from `corpus.bnf`. DO NOT EDIT.
//!
//! The columns the writer emits, and what each one IS. `corpus.bnf` carries the
//! rows and the argument; this is the Rust projection of them.
//!
//! **Read a set by the ROLES it means, not by a name you remember.** The two
//! consumers that used to carry hand-written lists meant different things by
//! "the writer's columns" and nothing said so — see `corpus.bnf`.

/// What a column IS — never what a reader does with it.
///
/// A reader that used to carry a list now names the roles it means.
/// It is data in `fossil.json` too: a writer column's `role` in its
/// table's `properties`, spelled as the variant in lowercase.
#[derive(
    Debug,
    Clone,
    Copy,
    PartialEq,
    Eq,
    PartialOrd,
    Ord,
    Hash,
    serde::Serialize,
    serde::Deserialize,
    schemars::JsonSchema,
)]
#[serde(rename_all = "lowercase")]
pub enum ColumnRole {
    /// The row's rank in the ordering, which a new subject renumbers.
    Address,
    /// What a bookmark keys on, and what survives a rebuild.
    Identity,
    /// One end of a relation, a vertex's global `dense_id`.
    Endpoint,
}

/// One column the writer emits.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct WriterColumn {
    /// The column name, as it appears in the Parquet schema.
    pub name: &'static str,
    /// The manifest's spelling of its type, which is what the manifest writes.
    pub data_type: &'static str,
    pub role: ColumnRole,
}

/// Every column of a vertex payload row, in writer order.
pub const PAYLOAD_COLUMNS: &[WriterColumn] = &[
    WriterColumn {
        name: "dense_id",
        data_type: "uint32",
        role: ColumnRole::Address,
    },
    WriterColumn {
        name: "subject",
        data_type: "string",
        role: ColumnRole::Identity,
    },
];

/// The address column of a vertex payload row — the row's rank in the ordering, which a new subject renumbers.
pub const PAYLOAD_ADDRESS: &str = "dense_id";

/// The identity column of a vertex payload row — what a bookmark keys on, and what survives a rebuild.
pub const PAYLOAD_IDENTITY: &str = "subject";

/// Every column of an edge row, in writer order.
pub const EDGE_COLUMNS: &[WriterColumn] = &[
    WriterColumn {
        name: "src",
        data_type: "uint32",
        role: ColumnRole::Endpoint,
    },
    WriterColumn {
        name: "dst",
        data_type: "uint32",
        role: ColumnRole::Endpoint,
    },
];

/// The edge column the manifest's `source` endpoint names as its `key`.
pub const ENDPOINT_SRC: &str = "src";

/// The edge column the manifest's `destination` endpoint names as its `key`.
pub const ENDPOINT_DST: &str = "dst";
