//! TypeScript declarations from a JSON Schema, as `schemars` derives one.
//!
//! The dialect is what `schemars` 0.8 emits for a serde type and nothing more:
//! `$ref`, a one-element `allOf` around a `$ref`, `const`, `enum`, `oneOf` and
//! `anyOf`, the five JSON types (one or a `[…, "null"]` pair), arrays, objects
//! with `properties`, maps as `additionalProperties`, and the unconstrained
//! schema, which is `unknown`. Anything else panics
//! naming the schema, because a declaration that silently widens to `unknown`
//! is the drift generation exists to stop.

use std::fmt::Write as _;

use serde_json::Value;

/// The TypeScript type a schema denotes.
///
/// # Panics
/// On a schema outside the dialect in the module docs.
#[must_use]
pub fn ty(schema: &Value) -> String {
    if let Some(r) = schema["$ref"].as_str() {
        return r
            .strip_prefix("#/definitions/")
            .unwrap_or_else(|| panic!("a `$ref` outside `#/definitions`: {r}"))
            .to_string();
    }
    if let Some(v) = schema.get("const") {
        return literal(v);
    }
    if let Some(values) = schema["enum"].as_array() {
        return union(values.iter().map(literal));
    }
    for key in ["allOf", "oneOf", "anyOf"] {
        if let Some(arms) = schema[key].as_array() {
            assert!(
                key != "allOf" || arms.len() == 1,
                "an `allOf` of more than one schema: {schema}"
            );
            return union(arms.iter().map(ty));
        }
    }
    match &schema["type"] {
        Value::String(name) => scalar(name, schema),
        Value::Array(names) => union(
            names
                .iter()
                .map(|n| scalar(n.as_str().expect("a type name"), schema)),
        ),
        // No constraint at all — `true`, or a schema that only describes — is
        // any JSON value.
        Value::Null
            if schema
                .as_object()
                .is_none_or(|o| o.keys().all(|k| k == "description")) =>
        {
            "unknown".into()
        }
        _ => panic!("a schema xtask cannot read: {schema}"),
    }
}

fn scalar(name: &str, schema: &Value) -> String {
    match name {
        "string" => "string".into(),
        "integer" | "number" => "number".into(),
        "boolean" => "boolean".into(),
        "null" => "null".into(),
        "array" => format!("{}[]", paren(&ty(&schema["items"]))),
        "object" => object(schema, ""),
        other => panic!("a JSON type xtask does not read: {other}"),
    }
}

/// An object's body: `{ … }` for properties, `Record<string, T>` for a map.
fn object(schema: &Value, indent: &str) -> String {
    let Some(props) = schema["properties"].as_object() else {
        let values = match &schema["additionalProperties"] {
            Value::Object(_) => ty(&schema["additionalProperties"]),
            _ => "unknown".into(),
        };
        return format!("Record<string, {values}>");
    };
    let required: Vec<&str> = schema["required"]
        .as_array()
        .map(|r| r.iter().filter_map(Value::as_str).collect())
        .unwrap_or_default();
    let inner = format!("{indent}  ");
    let mut out = String::from("{\n");
    for (name, prop) in props {
        doc(
            &mut out,
            &inner,
            prop["description"].as_str().unwrap_or_default(),
        );
        let optional = if required.contains(&name.as_str()) {
            ""
        } else {
            "?"
        };
        let _ = writeln!(out, "{inner}{}{optional}: {};", key(name), ty(prop));
    }
    out.push_str(indent);
    out.push('}');
    out
}

/// Every definition of `schema`, and the root itself when it has a `title`, as
/// exported declarations in name order.
#[must_use]
pub fn declarations(schema: &Value) -> String {
    let mut named: Vec<(&str, &Value)> = schema["definitions"]
        .as_object()
        .map(|d| d.iter().map(|(k, v)| (k.as_str(), v)).collect())
        .unwrap_or_default();
    if let Some(title) = schema["title"].as_str() {
        named.push((title, schema));
    }
    named.sort_by_key(|(name, _)| *name);
    let mut out = String::new();
    for (name, def) in named {
        out.push('\n');
        doc(
            &mut out,
            "",
            def["description"].as_str().unwrap_or_default(),
        );
        if def["type"] == "object" && def["properties"].is_object() {
            let _ = writeln!(out, "export interface {name} {}", object(def, ""));
        } else {
            let _ = writeln!(out, "export type {name} = {};", ty(def));
        }
    }
    out
}

/// A generated file's header: what made it and what to run instead of editing it.
#[must_use]
pub fn header(what: &str) -> String {
    format!(
        "// @generated by `crates/xtask/tests/wire.rs` from {what}. DO NOT EDIT:\n\
         // `UPDATE_EXPECT=1 cargo test -p xtask --test wire` rewrites it.\n"
    )
}

fn union(parts: impl Iterator<Item = String>) -> String {
    let mut parts: Vec<String> = parts.collect();
    parts.dedup();
    parts.join(" | ")
}

fn literal(v: &Value) -> String {
    match v {
        Value::String(s) => quote(s),
        other => other.to_string(),
    }
}

fn key(name: &str) -> String {
    if name.chars().all(|c| c.is_ascii_alphanumeric() || c == '_') {
        name.to_string()
    } else {
        quote(name)
    }
}

/// `a | b` as an array element needs parentheses; a single name does not.
fn paren(ts: &str) -> String {
    if ts.contains(' ') {
        format!("({ts})")
    } else {
        ts.to_string()
    }
}

/// A TypeScript single-quoted string literal.
#[must_use]
pub fn quote(s: &str) -> String {
    format!("'{}'", s.replace('\\', "\\\\").replace('\'', "\\'"))
}

/// A `JSDoc` block at `indent`, or nothing for empty text: rustdoc's links
/// unwrapped to their code span, each paragraph wrapped at 100 columns.
pub fn doc(out: &mut String, indent: &str, text: &str) {
    if text.is_empty() {
        return;
    }
    let width = 100 - indent.len() - 3;
    let _ = writeln!(out, "{indent}/**");
    for paragraph in unlink(text).replace("*/", "*\\/").lines() {
        let mut line = String::new();
        for word in paragraph.split_whitespace() {
            if !line.is_empty() && line.len() + 1 + word.len() > width {
                let _ = writeln!(out, "{indent} * {line}");
                line.clear();
            }
            if !line.is_empty() {
                line.push(' ');
            }
            line.push_str(word);
        }
        if line.is_empty() {
            let _ = writeln!(out, "{indent} *");
        } else {
            let _ = writeln!(out, "{indent} * {line}");
        }
    }
    let _ = writeln!(out, "{indent} */");
}

/// `` [`a::b`] `` and `` [`a`](path) `` as `` `a::b` `` and `` `a` ``.
fn unlink(text: &str) -> String {
    let mut out = String::with_capacity(text.len());
    let mut rest = text;
    while let Some(at) = rest.find("[`") {
        out.push_str(&rest[..at]);
        let code = &rest[at + 1..];
        let Some(close) = code[1..].find("`]").map(|i| i + 1) else {
            out.push_str(&rest[at..]);
            return out;
        };
        out.push_str(&code[..=close]);
        rest = &code[close + 2..];
        if rest.starts_with('(')
            && let Some(end) = rest.find(')')
        {
            rest = &rest[end + 1..];
        }
    }
    out.push_str(rest);
    out
}
