//! The Fossil v0.1 standard-library catalog — every function the language
//! declares, with its receiver, its signature and how it compiles.
//!
//! # Why it lives in `fossil-hir`
//!
//! The checker resolves a `HirExpr::Call` against this catalog: arity, argument
//! types and the result type all come from here. It used to be its own crate,
//! `fossil-registry`, which depended on `fossil-hir` for `FnSig` — so the
//! checker could not read it without a cycle, and for as long as that held, a
//! call could not be typed at all. The catalog is language surface, so it moved
//! down, not the checker up.
//!
//! # A row is DATA: receiver + name + signature + lowering
//!
//! **The catalogue IS a file the compiler reads.** `catalogue.bnf` carries every
//! row — both halves of it, the `io.` constructors and the stdlib — and
//! `cargo xtask catalogue` generates [`generated`] from it. `grammar.bnf` says
//! the SHAPE of a program and `catalogue.bnf` says WHICH NAMES EXIST: two data
//! files and a compiler. Adding `str.slugify` over `regexp_replace` is a line in
//! the file and touches no Rust.
//!
//! What is left in THIS module is the vocabulary the file is written in — the
//! receiver, the signature, the arities, the lowering kinds and [`PlanOp`] —
//! plus the queries the checker and the IDE ask of the assembled table. A type
//! cannot live in the file; the rows cannot live anywhere else.
//!
//! This paragraph used to read «Nothing here loads a file yet, and that is
//! deliberate: what this module owes the loader is a shape it can fill.» The
//! loader arrived and the shape fitted.
//!
//! ## The receiver is the field that ends dispatch-by-string
//!
//! `RegistryEntry::name` used to be the whole of the key — the string
//! `"clean.trim"` — and dispatch by RECEIVER TYPE exists to replace exactly
//! that. A row now says what it hangs off
//! (`Receiver`) and what it is called after the dot
//! (`RegistryEntry::member`), and both are derived in ONE place,
//! `split_receiver`, from the dotted name. They are not constructor
//! arguments: a field a call site fills by hand is a field that ends up
//! disagreeing with the name beside it.
//!
//! Three ways in, and each is a different question:
//!
//! - `FunctionRegistry::lookup` — the TYPE path, `str.trim(x)`. By dotted
//!   name, which is what a `HirExpr::Call` carries.
//! - `FunctionRegistry::lookup_member` — the VALUE path, `x.trim()`. By
//!   receiver and member, which is what a postfix call knows.
//! - `FunctionRegistry::members_of` — every member of a receiver. This is
//!   what makes completion stop being approximate: the IDE can ask what a
//!   value HAS instead of offering the whole catalogue.
//!
//! ## Two lowerings, and no third
//!
//! There is one border and it is semantic: `LoweringKind::Expr` is a scalar
//! SQL expression and `LoweringKind::Op` names an operator of the algebra, a
//! closed set — [`PlanOp`], and the size of it is not written here or anywhere
//! else: the enum is the one place that cannot be wrong about how many variants
//! it has. `Udf` is gone — see [`LoweringKind::Expr`] for what that cost and
//! bought.
//!
//! ## `WasmClass` is gone as a CONCEPT
//!
//! There was a `WasmClass` field, a `derive_wasm_class` that computed it, a
//! `NativeUdfOnly` variant and a test asserting `PureSql ⟺ non-Udf`. With no
//! `Udf` variant the bad state is unrepresentable rather than derived and
//! checked, so all four go, and `fossil-layout/src/udf.rs` with them. **The
//! language now runs entirely in the browser**, which is a change of product
//! and not of housekeeping.

use std::sync::LazyLock;

/// The catalogue itself: `catalogue.bnf`, as Rust.
///
/// Generated by `cargo xtask catalogue`; edit the `.bnf` and re-run it.
/// `crates/xtask/tests/catalogue_generated.rs` fails when the checked-in file
/// is stale.
mod generated;

use fossil_graph_schema::Primitive;
use smol_str::SmolStr;

use crate::ty::{Ty, TyKind};

/// The process-wide catalog.
///
/// The checker resolves every call against this, so it is built once rather
/// than per call. It is program-invariant in v0.1 — there is no federation and
/// no user-defined function, so nothing about a program can change it. When
/// that stops being true this becomes a Salsa input, and the call sites do not
/// move.
static STDLIB: LazyLock<FunctionRegistry> = LazyLock::new(FunctionRegistry::stdlib_default);

/// The stdlib catalog. See [`STDLIB`].
#[must_use]
pub fn stdlib() -> &'static FunctionRegistry {
    &STDLIB
}

/// Every catalogue row that is an aggregate, spelled and sorted, for a message.
///
/// Derived, like `crate::lower::lowered_verbs` and for the same reason: the
/// list a user is shown and the list the checker admits have to be one list, or
/// the message goes stale on its own and nothing turns red.
#[must_use]
pub fn aggregate_names() -> Vec<String> {
    let mut names: Vec<String> = STDLIB
        .entries
        .values()
        .filter(|e| e.agg_fn().is_some())
        .map(|e| format!("`{}`", e.name))
        .collect();
    names.sort();
    names
}
use std::collections::HashMap;

/// Registry of stdlib functions available to a Fossil program.
///
/// Construct via [`Self::stdlib_default`]. Read a row by its dotted name with
/// [`Self::lookup`], by receiver and member with [`Self::lookup_member`], and
/// enumerate a receiver's members with [`Self::members_of`].
#[derive(Debug, Clone)]
pub struct FunctionRegistry {
    entries: HashMap<SmolStr, RegistryEntry>,
}

/// What sits to the LEFT of the dot, and therefore what decides which members
/// exist (`grammar.bnf`, `PostfixExpr`).
///
/// This is the field that turns dispatch from a string match into a type
/// question. Before it, `where` / `select` / `join` were productions in the
/// grammar and everything else was looked up by its dotted spelling, so a new
/// verb meant a new RULE. With a receiver on every row, **a new verb is a ROW.**
///
/// The three variants are the three things the grammar says can stand on the
/// left, reduced to what the checker can actually dispatch on:
///
/// - [`Self::Namespace`] — `io`, `core`, `parse`, `math`.
///   A name, not a value: there is nothing to dispatch on, so the entry is
///   reached by its dotted spelling and only that. `io` is the clearest case —
///   its entries **create** the thing, so they cannot have a receiver.
/// - [`Self::Scalar`] — a value's type. Reached by EITHER path, and both reach
///   ONE row: `str.lower(x)` and `x.lower()` resolve to the same entry,
///   exactly as `str::len(&s)` ≡ `s.len()` in Rust. One entry, two ways in.
/// - [`Self::Relation`] — a relation (`Users`, `Adults`). Its members are the
///   verbs — `where`, `select`, `join` — which is why a new verb is a row.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Receiver {
    /// No receiver — a namespace function, reached only as `ns.member(args)`.
    Namespace,
    /// A value of this scalar type. Reached as `Ty.member(x, …)` or
    /// `x.member(…)`; both are the same row.
    Scalar(ScalarTy),
    /// A relation. Reached as `Rel.member(…)`; the members are the verbs.
    Relation,
}

/// The receiver a namespace-or-type head denotes, and the single place the
/// classification lives.
///
/// Derived from the head of the dotted name so that a row cannot carry a
/// receiver that disagrees with its own spelling. In the declarative catalogue
/// this becomes a column and this function becomes its parser; until then it is
/// the parser of a column that is written as the head of the name.
///
/// `str` and `seq` are TYPES, not namespaces: the left of a dot names a thing
/// whose members these are.
#[must_use]
pub fn receiver_of(head: &str) -> Receiver {
    match head {
        "str" => Receiver::Scalar(ScalarTy::String),
        "seq" => Receiver::Relation,
        _ => Receiver::Namespace,
    }
}

/// Split a dotted catalogue name into its receiver and its member.
///
/// The ONE place `recv` and `member` come from. Both are derived rather than
/// passed, because a field a call site sets by hand is a field that drifts from
/// the name written beside it — which is the defect this whole change is about,
/// one level down.
///
/// A name with no dot is not a catalogue name; it gets [`Receiver::Namespace`]
/// and itself as the member, so a malformed row is inert rather than a panic.
#[must_use]
pub fn split_receiver(dotted: &str) -> (Receiver, SmolStr) {
    dotted.split_once('.').map_or_else(
        || (Receiver::Namespace, SmolStr::new(dotted)),
        |(head, member)| (receiver_of(head), SmolStr::new(member)),
    )
}

/// A single stdlib function entry — one ROW of the catalogue.
///
/// Four fields, all data: the `Receiver` it hangs off, its name, a `'db`-free
/// [`SigSpec`], and its `LoweringKind`. `recv` and `member` are derived from
/// `name` by `split_receiver` at construction and are never passed in.
#[derive(Debug, Clone)]
pub struct RegistryEntry {
    /// Fully-qualified dotted name (e.g. `"str.trim"`, `"io.csv"`).
    ///
    /// Still the catalogue's key, because a namespace entry has no other handle.
    /// For a [`Receiver::Scalar`] or [`Receiver::Relation`] row it is the
    /// TYPE-PATH spelling: the left half names a type, not a namespace.
    pub name: SmolStr,
    /// What this entry hangs off. See `Receiver`.
    pub recv: Receiver,
    /// The name after the dot — the member. `"lower"` for `str.lower`, `"where"`
    /// for the relation verb. This is what a value-path call `x.lower()` matches
    /// on, and it is why the type path `str.lower(x)` and the value path
    /// `x.lower()` reach one row.
    pub member: SmolStr,
    /// `'db`-free signature description. The checker reads it directly —
    /// `param.ty.to_ty(db)` — and there is no interned form of it.
    pub sig: SigSpec,
    /// How this row compiles: a scalar SQL expression, or an operator.
    pub lowering: LoweringKind,
}

impl RegistryEntry {
    /// Build one row, deriving its receiver and member from its dotted name.
    ///
    /// The ONE constructor, and the reason `recv` and `member` are not
    /// parameters: a field a caller fills by hand is a field that ends up
    /// disagreeing with the name beside it. `crate::stdlib::generated` is the
    /// only caller, and it cannot express the disagreement because this
    /// signature has nowhere to put one.
    #[must_use]
    pub fn new(name: &str, params: Vec<ParamSpec>, ret: SigTy, lowering: LoweringKind) -> Self {
        let (recv, member) = split_receiver(name);
        Self {
            name: SmolStr::new(name),
            recv,
            member,
            sig: SigSpec::new(params, ret),
            lowering,
        }
    }

    /// The aggregate this row is, if it is one.
    ///
    /// Beside [`LoweringKind`] rather than inside it: the template stays, and
    /// `sum(%0)` IS the SQL a scalar rendering of this row emits, so the four
    /// are still covered by the guards that bind every template against a real
    /// `DuckDB`. What was missing is only which operator of the algebra a call
    /// becomes when it is written inside a `group_by`.
    ///
    /// `stdlib::tests::every_aggregate_names_a_row` is why this cannot drift
    /// into naming a row the catalogue does not have.
    #[must_use]
    pub fn agg_fn(&self) -> Option<AggFn> {
        match self.name.as_str() {
            "math.sum" => Some(AggFn::Sum),
            "math.min" => Some(AggFn::Min),
            "math.max" => Some(AggFn::Max),
            "math.avg" => Some(AggFn::Avg),
            _ => None,
        }
    }
}

/// A `'db`-free description of a function signature: the param scalar types and
/// the return scalar type.
///
/// Stored in the static registry so a [`RegistryEntry`] needs no `'db` lifetime.
/// A parameter's type is resolved one at a time, where it is checked.
///
/// v0.1 limitation: the surface syntax for schema-directed parsing (`parse.json`
/// and the `seq/` higher-order arguments) does not exist yet, so signatures here
/// are the best scalar approximation. Generic / higher-order positions collapse
/// to their dominant scalar shape.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct SigSpec {
    /// Each parameter's NAME and scalar type, in order.
    pub params: Vec<ParamSpec>,
    /// What the row gives back.
    pub ret: SigTy,
}

/// One parameter of a catalogue row: what it is called, and what it takes.
///
/// The name is here and nowhere else, and that placement is the whole of the
/// named-argument decision (`grammar.bnf`, `NamedArg`). `NamedArg := IDENT ASSIGN
/// Expression` is a production, so the grammar is normative and `format =
/// "%Y-%m-%d"` is a program fossil must accept; what it needed was somewhere for
/// `format` to MEAN something. A signature is that somewhere:
///
/// - it is where arity and argument types are already checked, so a name that
///   matches no parameter is refused beside a count that does not match;
/// - it makes the resolution PURELY LOCAL — `crate::lower` reorders the
///   arguments into positional slots against this vector and every layer below
///   the HIR keeps seeing positional arguments. `HirExpr::Call` did not change,
///   MIR did not change, and the backends did not change.
///
/// The rejected alternative was to carry names into `HirExpr::Call` and resolve
/// them in the checker. It costs a wider HIR for nothing: no diagnostic the
/// checker could give is better than one given where the source text is still in
/// hand, and every consumer of `Call` would then have to know that arguments may
/// be out of order.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ParamSpec {
    /// What a named argument writes to reach this position.
    pub name: SmolStr,
    /// What it takes.
    pub ty: SigTy,
    /// How many arguments fill this position. See [`Arity`].
    pub arity: Arity,
    /// Whether this position is written WITH its name — `on = …` — rather than
    /// by position.
    ///
    /// A property of the row because it is a property of the surface:
    /// `grammar.bnf` spells a join `join(User, on = …)`, and a bare predicate in
    /// the second slot is a different program. Without this the binder would
    /// fill the position from either spelling and `join(User, a == b)` would
    /// start compiling — a widening of the language arrived at by accident,
    /// which is the failure this whole change exists to stop making possible.
    ///
    /// One row uses it. It is here rather than special-cased there because a
    /// special case in the binder is the hand-written arm coming back.
    pub named: bool,
}

impl ParamSpec {
    /// Is this position filled by COUNTING, rather than by being named?
    ///
    /// The single place the distinction is drawn, and it has two sources rather
    /// than one: a position written with its name ([`Self::named`]), and a
    /// [`SigTy::Aggregate`], which is reached by collecting every named argument
    /// no other parameter claimed. Both are named; only the first says so in a
    /// flag, which is why asking the flag alone gets `seq.group_by` wrong.
    ///
    /// [`assert_repetition_is_last_and_positional`] is the reason this exists:
    /// the ambiguity a repetition creates is an ambiguity of counting.
    #[must_use]
    pub const fn is_positional(&self) -> bool {
        !self.named && !matches!(self.ty, SigTy::Aggregate)
    }
}

/// How many arguments one parameter position takes.
///
/// A position was implicitly [`Self::One`] and nothing could say otherwise, so
/// `seq.select`'s list of columns was unwritable in a signature and lived in a
/// hand-written arm instead. It is also why `str.concat` is documented variadic
/// while the row takes two: the page could write a repetition the row could not.
///
/// # The repetition rule, stated precisely
///
/// It is NOT «at most one position repeats and it is the last»:
/// `seq.group_by` has TWO [`Self::OneOrMore`] positions (`keys` and
/// `aggregations`), and nothing in `stdlib_default` closes over such a rule.
///
/// The real rule is about POSITIONAL arguments, which is where the ambiguity
/// actually lives: a repetition in the middle cannot be told from the position
/// after it, because both are reached by counting. A position reached by NAME is
/// not reached by counting and cannot collide with anything.
///
/// > **Among the positions filled POSITIONALLY, at most one repeats, and it is
/// > the last of them.**
///
/// A position is filled positionally unless it is written with its name
/// ([`ParamSpec::named`]) or it is a [`SigTy::Aggregate`], which collects every
/// named argument no other parameter claimed. That is why `group_by`'s two
/// repetitions do not collide: only `keys` is positional.
///
/// [`assert_repetition_is_last_and_positional`] is the check, and
/// `FunctionRegistry::stdlib_default` now runs it over every row.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub enum Arity {
    /// Exactly one argument. Every scalar row's every position.
    #[default]
    One,
    /// One or more, and it must be the last position: `select(User.id, User.name)`.
    OneOrMore,
    /// Zero or one. A named argument a row can do without.
    Optional,
}

/// **Among the positions filled POSITIONALLY, at most one repeats, and it is the
/// last of them.** See [`Arity`] for why the rule is about positional arguments
/// and not about all of them.
///
/// This is the check [`Arity`]'s doc claimed was already here. Writing it turned
/// up nothing — every row obeys the rule once the rule is stated correctly —
/// which is the outcome an assertion should have, and is not an argument for
/// having left the sentence unbacked.
///
/// # Panics
///
/// If a row repeats a positional argument that is not its last positional one.
fn assert_repetition_is_last_and_positional(row: &RegistryEntry) {
    let positional: Vec<&ParamSpec> = row
        .sig
        .params
        .iter()
        .filter(|p| p.is_positional())
        .collect();
    for (i, p) in positional.iter().enumerate() {
        assert!(
            p.arity != Arity::OneOrMore || i + 1 == positional.len(),
            "`{}` repeats the positional parameter `{}`, which is not its last \
             positional one — a repetition in the middle cannot be told from the \
             position after it",
            row.name,
            p.name
        );
    }
}

/// What a catalogue row's parameter takes, or what it gives back.
///
/// It was [`ScalarTy`] alone, and the `seq/` rows were written
/// `p("rows", S::String)` under a comment reading «higher-order arguments
/// collapse to scalar placeholders in v0.1». They did not collapse; there was
/// nothing to collapse INTO, because a relation was not a type. It is
/// [`crate::ty::TyKind::Relation`] now, and these two variants are the rest of
/// the notation:
///
/// - [`Self::Rows`] is the relation a verb is a verb OF, and every `seq/` row's
///   parameter 0;
/// - [`Self::Predicate`] is an expression over that relation's row, yielding
///   `Bool` — what `where` takes and what a `join`'s `on` condition is.
///
/// It is the shape five reference systems arrive at from different directions:
/// `pg_proc`'s argument types over a catalogue, GHC's `primops.txt.pp`, Trino's
/// and `DuckDB`'s function tables, and PRQL's `{arg:N}`. What none of them needed
/// and this does is a parameter whose type depends on the RECEIVER's, which is
/// why `Rows` and `Predicate` are variants and not two more scalars.
///
/// # The two that name rather than evaluate
///
/// [`Self::Column`] and [`Self::Binding`] are that same argument read once more.
/// A `select`'s arguments are not values: `select(User.id)` does not evaluate
/// `User.id`, it NAMES a column of the receiver's rows, and `join(User, …)`
/// names a source binding. Both depend on the receiver exactly as `Predicate`
/// does, so both are variants here for the reason the ones above are.
///
/// They were absent, and the absence is measurable rather than theoretical. A
/// relation row's signature said only `rows("rows")` — one parameter, the
/// receiver — so the rest of what a verb takes had to be written down
/// somewhere else, and the somewhere else was one hand-written arm per verb in
/// `crate::lower`. Two things followed. `crates/xtask/src/reference.rs` measured
/// the first: the reference page INVENTED parameters for `seq.sort`,
/// `seq.distinct` and `seq.group_by` — `by`, `key`, `desc` — because their
/// signature had none to print and prose filled the hole. The second is that
/// arity and named-argument resolution, which [`SigSpec`] exists to do once,
/// were done a third time per arm in three different wordings.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum SigTy {
    /// A value of a scalar type.
    Scalar(ScalarTy),
    /// The receiver relation, with whatever rows it carries.
    Rows,
    /// A condition over the receiver's rows.
    ///
    /// **This is the wider of the two readings, and `join` takes the narrower
    /// one.** A `where`'s predicate is any expression yielding `Bool`; a join's
    /// `on` is a conjunction of equalities, each between a column of one side
    /// and a column of the other, and that extra rule is
    /// `crate::infer::check_join_condition` rather than a second variant here.
    /// It is not a type: `on = Purchase.id == Purchase.user_id` has exactly the
    /// type `on = Purchase.user_id == User.id` has, and what separates them is
    /// which relations the columns came from — which the signature has no place
    /// to say and the scope at the join does.
    Predicate,
    /// The NAME of a column of the receiver's rows, qualified by the binding
    /// that owns it — `select(User.id)`, `sort(User.name)`, `group_by(User.city)`.
    ///
    /// Not a [`Self::Scalar`] of unknown type: the difference is not what it
    /// evaluates to but that it is not evaluated. `crate::lower` reads it off
    /// the CST as a [`crate::lower::SelectedColumn`], and open question 4 of
    /// `grammar.bnf` decided the qualification travels with it.
    Column,
    /// The NAME of a source binding, with `X as Y` optional — the right side of
    /// a join.
    ///
    /// The alias is part of this position and not a parameter of its own:
    /// `AliasArg := IDENT 'as' IDENT` is one production, and a self-join's
    /// second name is the only thing that can tell two sides apart once both
    /// are the same binding.
    Binding,
    /// `total = math.sum(Order.amount)` — an aggregate over the group, under
    /// the name its column will answer to.
    ///
    /// The only position whose ARGUMENT NAMES are the program's rather than the
    /// row's, and it is what a `group_by` needs that no other verb does: the
    /// out-column of an aggregate has to be called something, and a signature
    /// cannot declare a name a user is going to invent. So the binder collects
    /// every named argument no other parameter claimed, and [`ParamSpec::name`]
    /// here is the position's label for a message and not a key to reach it by.
    Aggregate,
}

impl SigTy {
    /// The scalar this position takes, or `None` when it takes a relation, a
    /// condition or a name — none of which a `'static` tag can describe,
    /// because all of them depend on the receiver.
    #[must_use]
    pub const fn scalar(self) -> Option<ScalarTy> {
        match self {
            Self::Scalar(s) => Some(s),
            Self::Rows | Self::Predicate | Self::Column | Self::Binding | Self::Aggregate => None,
        }
    }

    /// Whether this position NAMES something instead of evaluating to a value.
    ///
    /// The single place the distinction is drawn, because three consumers need
    /// it and each would otherwise draw it again: `crate::lower` reads the CST
    /// differently, `crate::infer` has nothing to type-check here, and
    /// `xtask::reference` renders `User.id` rather than an expression.
    #[must_use]
    pub const fn names_rather_than_evaluates(self) -> bool {
        matches!(self, Self::Column | Self::Binding)
    }
}

impl From<ScalarTy> for SigTy {
    fn from(s: ScalarTy) -> Self {
        Self::Scalar(s)
    }
}

impl SigSpec {
    /// Convenience constructor.
    #[must_use]
    pub const fn new(params: Vec<ParamSpec>, ret: SigTy) -> Self {
        Self { params, ret }
    }

    /// The zero-based position `name` refers to, or `None` if this signature has
    /// no such parameter.
    #[must_use]
    pub fn position_of(&self, name: &str) -> Option<usize> {
        self.params.iter().position(|p| p.name == name)
    }
}

/// A `'db`-free scalar-type tag, mirroring the subset of `fossil_hir::TyKind`
/// the v0.1 stdlib signatures need. Resolved to a `Ty<'db>` by [`Self::to_ty`].
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ScalarTy {
    /// `xsd:string`.
    String,
    /// `xsd:integer`.
    Integer,
    /// `xsd:float` / `xsd:double`.
    Float,
    /// `xsd:boolean`.
    Bool,
    /// `xsd:date`.
    Date,
    /// `xsd:dateTime`.
    DateTime,
    // An `Iri` variant stood here and no row in the catalogue used it — a
    // signature can neither take nor return a reference, because a reference is
    // to a SHAPE and the catalogue names no shapes. When one does, it will need
    // to say WHICH, which is not a scalar tag.
    /// `Seq<String>` — the one repeated shape v0.1 needs (`str.split`).
    SeqString,
}

impl ScalarTy {
    /// Intern this tag into a `Ty<'db>` via the fossil-hir constructor.
    #[must_use]
    pub fn to_ty(self, db: &dyn salsa::Database) -> Ty<'_> {
        let kind = match self {
            Self::String => TyKind::Primitive(Primitive::String),
            Self::Integer => TyKind::Primitive(Primitive::Integer),
            Self::Float => TyKind::Primitive(Primitive::Float),
            Self::Bool => TyKind::Primitive(Primitive::Bool),
            Self::Date => TyKind::Primitive(Primitive::Date),
            Self::DateTime => TyKind::Primitive(Primitive::DateTime),
            Self::SeqString => {
                let s = Ty::new(db, TyKind::Primitive(Primitive::String));
                TyKind::Seq(s)
            }
        };
        Ty::new(db, kind)
    }
}

/// How a stdlib row compiles. TWO variants, and the border between them is the
/// only one that was ever semantic.
///
/// # `Expr` — a scalar SQL expression, written as a template
///
/// The payload is SQL text with `%N` holes, `N` the ZERO-BASED index of an
/// argument. `trim(%0)`, `CAST(%0 AS BIGINT)`, `%0 || %1`.
///
/// **Why indexed holes and not sequential ones.** A `?`-style placeholder that
/// consumes the next argument cannot express the two shapes the catalogue
/// actually contains, and both are load-bearing:
///
/// - a hole appearing **twice** — `core.require` is
///   `CASE WHEN %0 IS NULL THEN error(…) ELSE %0 END`, one argument read in two
///   positions. Sequential placeholders would demand two arguments for a
///   one-argument function;
/// - a hole appearing **zero** times — `anon.redact` is the literal
///   `'[REDACTED]'` and ignores what it is given. Sequential placeholders
///   cannot say "ignore".
///
/// So a template does NOT determine arity, and must not: [`SigSpec`] does, and
/// the checker reads it. A hole index outside the signature is a catalogue bug
/// that `crate::stdlib::tests` catches, not a runtime one.
///
/// **The one shape this notation does not have is the variadic**, and that is a
/// deliberate hole rather than an oversight. `Concat` was the only variadic
/// form and it belonged to `core.triple`, which was deleted with the other five
/// RDF term constructors; `BlankNode` was the only template referring to
/// something that is not an argument at all (`'_:bnode_' || row_id`) and
/// belonged to `core.blank`, deleted in the same sweep. Two of the four arity
/// puzzles this notation had to answer answered themselves by being
/// unreachable, and the remaining two are the two above. A variadic row needs a
/// notation and there is no row that needs one.
///
/// # `Op` — an operator of the algebra
///
/// [`PlanOp`] cuts at a real seam: it names one of a closed set of operators
/// that affect the PLAN, not a value. It used to be called `Plan`, after its
/// effect, rather than after what it names.
///
/// # What `Udf` cost, and what deleting it bought
///
/// There was a third kind, `Udf`, naming a native Rust function registered on a
/// `DuckDB` connection. Eight rows used it. Two are deleted from the language
/// outright because they cannot be done honestly without Rust — `anon.hmac`
/// (HMAC needs a key schedule and `DuckDB` has `sha256` and no HMAC) and
/// `clean.normalize_unicode` (`DuckDB` ships `nfc_normalize`, which is NFC and
/// nothing else). The other six are templates here, and each one's delta
/// against its Rust predecessor was measured, not assumed.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum LoweringKind {
    /// A scalar SQL expression template with `%N` argument holes.
    Expr(SmolStr),
    /// An operator of the algebra — affects the plan, not a value.
    Op(PlanOp),
}

/// The aggregate a `math/` row becomes inside a `group_by`.
///
/// It lived in `fossil-mir`, as an enum with a `Count` variant nothing
/// constructed, beside a `math/` half of this catalogue that said nothing about
/// being aggregates at all — «`math.sum`, `math.avg`, `math.min` and `math.max`
/// are the four that go inside `aggregate`. Nothing in the rows says so.»
/// [`RegistryEntry::agg_fn`] is the row saying so, and this is what it answers.
///
/// There is no `Count`: no row of the catalogue is a per-group count.
/// `seq.count` takes a whole relation and hands back an `Integer`, which is a
/// verb and not an aggregation, and a variant nothing can build is what
/// `Op::Distinct`'s `by` was.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, salsa::Update)]
pub enum AggFn {
    Sum,
    Min,
    Max,
    Avg,
}

/// Operators of the algebra: the relation verbs plus the `io/` sources.
///
/// A variant says *this name is an operator of the algebra, not a scalar
/// template*; what it lowers to is written beside it. The names are NOT a
/// mirror of `fossil-mir`'s `Op` — this crate has no `fossil-mir` dependency,
/// the direction of the graph forbids adding one, and `Take`/`Drop`/`Sort`/
/// `Flatten`/`Count` have no `Op` of their own in any case.
///
/// `crate::lower::lower_source_stage` matches this enum exhaustively, so a new
/// variant is a compile error there and no count is written down anywhere.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum PlanOp {
    /// `seq.where` → `FilterOp` (`WHERE`).
    Where,
    /// `seq.map` → `ExtendOp`s + `ProjectOp`.
    Map,
    /// `seq.flatten` → `UNNEST`.
    Flatten,
    /// `seq.take` → `LIMIT n`.
    Take,
    /// `seq.drop` → `OFFSET n`.
    Drop,
    /// `seq.distinct` → `SELECT DISTINCT`, over the whole row.
    Distinct,
    /// `seq.sort` → `ORDER BY`.
    Sort,
    /// `seq.select` → `ProjectOp` (`SELECT cols`).
    Select,
    /// `seq.join` → `JoinOp` (`JOIN ... ON`).
    Join,
    /// `seq.union` → `UNION ALL`.
    Union,
    /// `seq.group_by` → `SELECT keys, aggs … GROUP BY keys`.
    GroupBy,
    /// `seq.count` → `COUNT(*)`.
    Count,
    /// An `io/` source constructor. **Which** reader it is is not written here.
    ///
    /// The format comes from the PROVIDER ROW —
    /// `fossil-mir::lower::resolve_source` reads `Provider::reads_rows` — so
    /// naming it here as well would be that table said a second time. This row
    /// says only what a `HirExpr::Call` needs it to say: *this name is a source,
    /// not a scalar expression*.
    Source,
}

// ── Source dispatch is NOT here ───────────────────────────────────────────
//
// A source's name, the extensions it accepts and what it does with them are
// one table, `fossil_base::providers::Provider`, and it cannot live here even
// if it wanted to: a row that reads TYPES carries a `fn` into a schema
// language, and `fossil-hir` may not link one (`0e6898d`). It comes from the
// host, through `System::providers`.
//
// `FunctionRegistry` below is NOT that table and does not merge into it: it
// carries call SIGNATURES for the checker, and `io.csv` appears in both for the
// same reason `str.trim` appears in one — a provider is a thing you can name,
// a signature is what happens when you call it.

impl FunctionRegistry {
    /// Construct the stdlib catalog from the generated table.
    ///
    /// The table itself is `catalogue.bnf`, and `crate::stdlib::generated` is
    /// what `cargo xtask catalogue` makes of it. This function is what is left
    /// once the rows are data: it indexes them by name and checks the one
    /// invariant a row cannot state about itself.
    ///
    /// # Panics
    ///
    /// If two rows share a name, or if a row repeats a position that is not its
    /// last POSITIONAL one — see [`Arity`].
    #[must_use]
    pub fn stdlib_default() -> Self {
        let mut entries: HashMap<SmolStr, RegistryEntry> = HashMap::new();
        for row in generated::rows() {
            let name = row.name.clone();
            assert!(
                entries.insert(name.clone(), row).is_none(),
                "`{name}` is catalogued twice"
            );
        }
        for row in entries.values() {
            assert_repetition_is_last_and_positional(row);
        }
        Self { entries }
    }

    /// Lookup a row by fully-qualified dotted name — the TYPE path,
    /// `str.trim(x)`. Returns `None` if the name is unknown.
    #[must_use]
    pub fn lookup(&self, name: &str) -> Option<&RegistryEntry> {
        self.entries.get(name)
    }

    /// Lookup a row by RECEIVER and MEMBER — the VALUE path, `x.trim()`.
    ///
    /// This and [`Self::lookup`] reach the same row for a
    /// [`Receiver::Scalar`] entry: one entry, two ways in, and no second row
    /// to keep in step.
    #[must_use]
    pub fn lookup_member(&self, recv: Receiver, member: &str) -> Option<&RegistryEntry> {
        self.entries
            .values()
            .find(|e| e.recv == recv && e.member == member)
    }

    /// Every member of a receiver, unordered.
    ///
    /// The query that makes completion stop being approximate: an IDE asks
    /// what a value HAS instead of offering the catalogue and hoping.
    pub fn members_of(&self, recv: Receiver) -> impl Iterator<Item = &RegistryEntry> {
        self.entries.values().filter(move |e| e.recv == recv)
    }

    /// Every row whose member is spelled `member`, across all receivers.
    ///
    /// The value path knows the member before it knows the receiver's type, so
    /// this is what a lowering can ask. Exactly one hit is a resolution; more
    /// than one needs the type and is the checker's to settle.
    pub fn candidates_for_member(&self, member: &str) -> impl Iterator<Item = &RegistryEntry> {
        self.entries
            .values()
            .filter(move |e| e.member == member && e.recv != Receiver::Namespace)
    }

    /// Is `head` the left half of any catalogued name?
    ///
    /// What separates `str.slug` from `orders.user_id` used to be an
    /// open-coded `starts_with(&format!("{head}."))` scan in the lowering. It is
    /// a question about the catalogue, so it lives here.
    #[must_use]
    pub fn is_catalogued_head(&self, head: &str) -> bool {
        let prefix = format!("{head}.");
        self.entries.keys().any(|k| k.starts_with(&prefix))
    }

    /// Iterate every registered entry (unspecified order).
    pub fn iter(&self) -> impl Iterator<Item = &RegistryEntry> {
        self.entries.values()
    }
}

// ── The templates are NOT here any more ────────────────────────
//
// `SLUG_TEMPLATE` and `STRIP_HTML_TEMPLATE` stood here as `const`s, each under
// the fuzzing result that justified its exact text — 16/16 and 0 mismatches
// over 240,998 inputs for the first, 27/29 and 1,837 over 120,000 for the
// second. Both the value and the paragraph are in `catalogue.bnf` now, above
// the row they are about, which is where that file already keeps every argument
// it makes. Five `VALIDATE_*_TEMPLATE` consts went with the namespace.
//
// The two helpers that built this table — `expr(template)` and `L(op)` — went
// too. They were sugar for writing a `LoweringKind` by hand, and nothing writes
// one by hand: `crate::stdlib::generated` spells the variant out.

/// Substitute a template's `%N` holes with the caller's rendered arguments.
///
/// The single renderer, so that a template means one thing everywhere. `%N` is
/// zero-based; `%%` is a literal `%`. A hole whose index is out of range is
/// left verbatim rather than dropped — a template that names an argument the
/// signature does not have is a catalogue bug, and a visible one beats SQL that
/// silently loses a term.
///
/// # Errors
///
/// Never. A malformed template renders to text that will fail to parse, which
/// is where it should be caught.
#[must_use]
pub fn render_template(template: &str, args: &[String]) -> String {
    let mut out = String::with_capacity(template.len());
    let bytes: Vec<char> = template.chars().collect();
    let mut i = 0;
    while i < bytes.len() {
        if bytes[i] != '%' {
            out.push(bytes[i]);
            i += 1;
            continue;
        }
        if i + 1 < bytes.len() && bytes[i + 1] == '%' {
            out.push('%');
            i += 2;
            continue;
        }
        let mut j = i + 1;
        let mut digits = String::new();
        while j < bytes.len() && bytes[j].is_ascii_digit() {
            digits.push(bytes[j]);
            j += 1;
        }
        if let Some(a) = digits.parse::<usize>().ok().and_then(|n| args.get(n)) {
            out.push_str(a);
            i = j;
        } else {
            out.push('%');
            i += 1;
        }
    }
    out
}

/// The `%N` hole indices a template names, ascending and deduplicated.
///
/// The catalogue's own guard reads this: a template may use fewer holes than
/// the signature has parameters (`anon.redact` uses none) and may repeat one
/// (`core.require` uses `%0` twice), but it may never name an index the
/// signature does not have.
#[must_use]
pub fn template_holes(template: &str) -> Vec<usize> {
    let chars: Vec<char> = template.chars().collect();
    let mut holes = Vec::new();
    let mut i = 0;
    while i < chars.len() {
        if chars[i] != '%' {
            i += 1;
            continue;
        }
        if i + 1 < chars.len() && chars[i + 1] == '%' {
            i += 2;
            continue;
        }
        let mut j = i + 1;
        let mut digits = String::new();
        while j < chars.len() && chars[j].is_ascii_digit() {
            digits.push(chars[j]);
            j += 1;
        }
        if let Ok(n) = digits.parse::<usize>() {
            holes.push(n);
            i = j;
        } else {
            i += 1;
        }
    }
    holes.sort_unstable();
    holes.dedup();
    holes
}

#[cfg(test)]
#[cfg(all(test, not(target_arch = "wasm32")))]
mod tests;
