//! @generated by `cargo xtask catalogue` from `catalogue.bnf`. DO NOT EDIT.
//!
//! The stdlib catalogue: every function the language declares, with its
//! signature and how it compiles. `crate::stdlib` owns the TYPES this
//! table is written in, and `FunctionRegistry::stdlib_default` is its only
//! consumer.
//!
//! Edit `catalogue.bnf` and re-run `cargo xtask catalogue`.

use smol_str::SmolStr;

use super::{Arity, LoweringKind, ParamSpec, PlanOp, RegistryEntry, ScalarTy, SigTy};

/// Every catalogue row, in `catalogue.bnf` order.
pub(super) fn rows() -> Vec<RegistryEntry> {
    vec![
        RegistryEntry::new(
            "core.lang",
            vec![
                ParamSpec {
                    name: SmolStr::new("value"),
                    ty: SigTy::Scalar(ScalarTy::String),
                    arity: Arity::One,
                    named: false,
                },
                ParamSpec {
                    name: SmolStr::new("tag"),
                    ty: SigTy::Scalar(ScalarTy::String),
                    arity: Arity::One,
                    named: false,
                },
            ],
            SigTy::Scalar(ScalarTy::String),
            LoweringKind::Expr(SmolStr::new("%0")),
        ),
        RegistryEntry::new(
            "seq.where",
            vec![
                ParamSpec {
                    name: SmolStr::new("rows"),
                    ty: SigTy::Rows,
                    arity: Arity::One,
                    named: false,
                },
                ParamSpec {
                    name: SmolStr::new("keep"),
                    ty: SigTy::Predicate,
                    arity: Arity::One,
                    named: false,
                },
            ],
            SigTy::Rows,
            LoweringKind::Op(PlanOp::Where),
        ),
        RegistryEntry::new(
            "seq.map",
            vec![ParamSpec {
                name: SmolStr::new("rows"),
                ty: SigTy::Rows,
                arity: Arity::One,
                named: false,
            }],
            SigTy::Rows,
            LoweringKind::Op(PlanOp::Map),
        ),
        RegistryEntry::new(
            "seq.flatten",
            vec![
                ParamSpec {
                    name: SmolStr::new("rows"),
                    ty: SigTy::Rows,
                    arity: Arity::One,
                    named: false,
                },
                ParamSpec {
                    name: SmolStr::new("of"),
                    ty: SigTy::Column,
                    arity: Arity::One,
                    named: false,
                },
            ],
            SigTy::Rows,
            LoweringKind::Op(PlanOp::Flatten),
        ),
        RegistryEntry::new(
            "seq.take",
            vec![
                ParamSpec {
                    name: SmolStr::new("rows"),
                    ty: SigTy::Rows,
                    arity: Arity::One,
                    named: false,
                },
                ParamSpec {
                    name: SmolStr::new("n"),
                    ty: SigTy::Scalar(ScalarTy::Integer),
                    arity: Arity::One,
                    named: false,
                },
            ],
            SigTy::Rows,
            LoweringKind::Op(PlanOp::Take),
        ),
        RegistryEntry::new(
            "seq.drop",
            vec![
                ParamSpec {
                    name: SmolStr::new("rows"),
                    ty: SigTy::Rows,
                    arity: Arity::One,
                    named: false,
                },
                ParamSpec {
                    name: SmolStr::new("n"),
                    ty: SigTy::Scalar(ScalarTy::Integer),
                    arity: Arity::One,
                    named: false,
                },
            ],
            SigTy::Rows,
            LoweringKind::Op(PlanOp::Drop),
        ),
        RegistryEntry::new(
            "seq.distinct",
            vec![ParamSpec {
                name: SmolStr::new("rows"),
                ty: SigTy::Rows,
                arity: Arity::One,
                named: false,
            }],
            SigTy::Rows,
            LoweringKind::Op(PlanOp::Distinct),
        ),
        RegistryEntry::new(
            "seq.sort",
            vec![
                ParamSpec {
                    name: SmolStr::new("rows"),
                    ty: SigTy::Rows,
                    arity: Arity::One,
                    named: false,
                },
                ParamSpec {
                    name: SmolStr::new("by"),
                    ty: SigTy::Column,
                    arity: Arity::OneOrMore,
                    named: false,
                },
            ],
            SigTy::Rows,
            LoweringKind::Op(PlanOp::Sort),
        ),
        RegistryEntry::new(
            "seq.select",
            vec![
                ParamSpec {
                    name: SmolStr::new("rows"),
                    ty: SigTy::Rows,
                    arity: Arity::One,
                    named: false,
                },
                ParamSpec {
                    name: SmolStr::new("cols"),
                    ty: SigTy::Column,
                    arity: Arity::OneOrMore,
                    named: false,
                },
            ],
            SigTy::Rows,
            LoweringKind::Op(PlanOp::Select),
        ),
        RegistryEntry::new(
            "seq.join",
            vec![
                ParamSpec {
                    name: SmolStr::new("rows"),
                    ty: SigTy::Rows,
                    arity: Arity::One,
                    named: false,
                },
                ParamSpec {
                    name: SmolStr::new("right"),
                    ty: SigTy::Binding,
                    arity: Arity::One,
                    named: false,
                },
                ParamSpec {
                    name: SmolStr::new("on"),
                    ty: SigTy::Predicate,
                    arity: Arity::One,
                    named: true,
                },
            ],
            SigTy::Rows,
            LoweringKind::Op(PlanOp::Join),
        ),
        RegistryEntry::new(
            "seq.union",
            vec![
                ParamSpec {
                    name: SmolStr::new("rows"),
                    ty: SigTy::Rows,
                    arity: Arity::One,
                    named: false,
                },
                ParamSpec {
                    name: SmolStr::new("other"),
                    ty: SigTy::Binding,
                    arity: Arity::One,
                    named: false,
                },
            ],
            SigTy::Rows,
            LoweringKind::Op(PlanOp::Union),
        ),
        RegistryEntry::new(
            "seq.group_by",
            vec![
                ParamSpec {
                    name: SmolStr::new("rows"),
                    ty: SigTy::Rows,
                    arity: Arity::One,
                    named: false,
                },
                ParamSpec {
                    name: SmolStr::new("keys"),
                    ty: SigTy::Column,
                    arity: Arity::OneOrMore,
                    named: false,
                },
                ParamSpec {
                    name: SmolStr::new("aggregations"),
                    ty: SigTy::Aggregate,
                    arity: Arity::OneOrMore,
                    named: false,
                },
            ],
            SigTy::Rows,
            LoweringKind::Op(PlanOp::GroupBy),
        ),
        RegistryEntry::new(
            "seq.count",
            vec![ParamSpec {
                name: SmolStr::new("rows"),
                ty: SigTy::Rows,
                arity: Arity::One,
                named: false,
            }],
            SigTy::Scalar(ScalarTy::Integer),
            LoweringKind::Op(PlanOp::Count),
        ),
        RegistryEntry::new(
            "str.length",
            vec![ParamSpec {
                name: SmolStr::new("text"),
                ty: SigTy::Scalar(ScalarTy::String),
                arity: Arity::One,
                named: false,
            }],
            SigTy::Scalar(ScalarTy::Integer),
            LoweringKind::Expr(SmolStr::new("length(%0)")),
        ),
        RegistryEntry::new(
            "str.slice",
            vec![
                ParamSpec {
                    name: SmolStr::new("text"),
                    ty: SigTy::Scalar(ScalarTy::String),
                    arity: Arity::One,
                    named: false,
                },
                ParamSpec {
                    name: SmolStr::new("start"),
                    ty: SigTy::Scalar(ScalarTy::Integer),
                    arity: Arity::One,
                    named: false,
                },
            ],
            SigTy::Scalar(ScalarTy::String),
            LoweringKind::Expr(SmolStr::new("substring(%0, %1)")),
        ),
        RegistryEntry::new(
            "str.contains",
            vec![
                ParamSpec {
                    name: SmolStr::new("text"),
                    ty: SigTy::Scalar(ScalarTy::String),
                    arity: Arity::One,
                    named: false,
                },
                ParamSpec {
                    name: SmolStr::new("needle"),
                    ty: SigTy::Scalar(ScalarTy::String),
                    arity: Arity::One,
                    named: false,
                },
            ],
            SigTy::Scalar(ScalarTy::Bool),
            LoweringKind::Expr(SmolStr::new("contains(%0, %1)")),
        ),
        RegistryEntry::new(
            "str.starts_with",
            vec![
                ParamSpec {
                    name: SmolStr::new("text"),
                    ty: SigTy::Scalar(ScalarTy::String),
                    arity: Arity::One,
                    named: false,
                },
                ParamSpec {
                    name: SmolStr::new("prefix"),
                    ty: SigTy::Scalar(ScalarTy::String),
                    arity: Arity::One,
                    named: false,
                },
            ],
            SigTy::Scalar(ScalarTy::Bool),
            LoweringKind::Expr(SmolStr::new("starts_with(%0, %1)")),
        ),
        RegistryEntry::new(
            "str.ends_with",
            vec![
                ParamSpec {
                    name: SmolStr::new("text"),
                    ty: SigTy::Scalar(ScalarTy::String),
                    arity: Arity::One,
                    named: false,
                },
                ParamSpec {
                    name: SmolStr::new("suffix"),
                    ty: SigTy::Scalar(ScalarTy::String),
                    arity: Arity::One,
                    named: false,
                },
            ],
            SigTy::Scalar(ScalarTy::Bool),
            LoweringKind::Expr(SmolStr::new("ends_with(%0, %1)")),
        ),
        RegistryEntry::new(
            "str.replace",
            vec![
                ParamSpec {
                    name: SmolStr::new("text"),
                    ty: SigTy::Scalar(ScalarTy::String),
                    arity: Arity::One,
                    named: false,
                },
                ParamSpec {
                    name: SmolStr::new("needle"),
                    ty: SigTy::Scalar(ScalarTy::String),
                    arity: Arity::One,
                    named: false,
                },
                ParamSpec {
                    name: SmolStr::new("replacement"),
                    ty: SigTy::Scalar(ScalarTy::String),
                    arity: Arity::One,
                    named: false,
                },
            ],
            SigTy::Scalar(ScalarTy::String),
            LoweringKind::Expr(SmolStr::new("replace(%0, %1, %2)")),
        ),
        RegistryEntry::new(
            "str.split",
            vec![
                ParamSpec {
                    name: SmolStr::new("text"),
                    ty: SigTy::Scalar(ScalarTy::String),
                    arity: Arity::One,
                    named: false,
                },
                ParamSpec {
                    name: SmolStr::new("separator"),
                    ty: SigTy::Scalar(ScalarTy::String),
                    arity: Arity::One,
                    named: false,
                },
            ],
            SigTy::Scalar(ScalarTy::SeqString),
            LoweringKind::Expr(SmolStr::new("string_split(%0, %1)")),
        ),
        RegistryEntry::new(
            "str.concat",
            vec![
                ParamSpec {
                    name: SmolStr::new("text"),
                    ty: SigTy::Scalar(ScalarTy::String),
                    arity: Arity::One,
                    named: false,
                },
                ParamSpec {
                    name: SmolStr::new("other"),
                    ty: SigTy::Scalar(ScalarTy::String),
                    arity: Arity::One,
                    named: false,
                },
            ],
            SigTy::Scalar(ScalarTy::String),
            LoweringKind::Expr(SmolStr::new("concat(%0, %1)")),
        ),
        RegistryEntry::new(
            "str.trim",
            vec![ParamSpec {
                name: SmolStr::new("text"),
                ty: SigTy::Scalar(ScalarTy::String),
                arity: Arity::One,
                named: false,
            }],
            SigTy::Scalar(ScalarTy::String),
            LoweringKind::Expr(SmolStr::new("trim(%0)")),
        ),
        RegistryEntry::new(
            "str.lower",
            vec![ParamSpec {
                name: SmolStr::new("text"),
                ty: SigTy::Scalar(ScalarTy::String),
                arity: Arity::One,
                named: false,
            }],
            SigTy::Scalar(ScalarTy::String),
            LoweringKind::Expr(SmolStr::new("lower(%0)")),
        ),
        RegistryEntry::new(
            "str.upper",
            vec![ParamSpec {
                name: SmolStr::new("text"),
                ty: SigTy::Scalar(ScalarTy::String),
                arity: Arity::One,
                named: false,
            }],
            SigTy::Scalar(ScalarTy::String),
            LoweringKind::Expr(SmolStr::new("upper(%0)")),
        ),
        RegistryEntry::new(
            "str.slug",
            vec![ParamSpec {
                name: SmolStr::new("text"),
                ty: SigTy::Scalar(ScalarTy::String),
                arity: Arity::One,
                named: false,
            }],
            SigTy::Scalar(ScalarTy::String),
            LoweringKind::Expr(SmolStr::new(
                "trim(regexp_replace(lower(trim(%0)), '[^\\p{L}\\p{N}.-]', '-', 'g'), '-')",
            )),
        ),
        RegistryEntry::new(
            "str.strip_html",
            vec![ParamSpec {
                name: SmolStr::new("text"),
                ty: SigTy::Scalar(ScalarTy::String),
                arity: Arity::One,
                named: false,
            }],
            SigTy::Scalar(ScalarTy::String),
            LoweringKind::Expr(SmolStr::new(
                "regexp_replace(%0, '<(?:>|$|[^\\s](?:\"[^\"]*\"|''[^'']*''|[^>\"''])*(?:>|$))', '', 'g')",
            )),
        ),
        RegistryEntry::new(
            "parse.integer",
            vec![ParamSpec {
                name: SmolStr::new("text"),
                ty: SigTy::Scalar(ScalarTy::String),
                arity: Arity::One,
                named: false,
            }],
            SigTy::Scalar(ScalarTy::Integer),
            LoweringKind::Expr(SmolStr::new("CAST(%0 AS BIGINT)")),
        ),
        RegistryEntry::new(
            "parse.float",
            vec![ParamSpec {
                name: SmolStr::new("text"),
                ty: SigTy::Scalar(ScalarTy::String),
                arity: Arity::One,
                named: false,
            }],
            SigTy::Scalar(ScalarTy::Float),
            LoweringKind::Expr(SmolStr::new("CAST(%0 AS DOUBLE)")),
        ),
        RegistryEntry::new(
            "parse.decimal",
            vec![ParamSpec {
                name: SmolStr::new("text"),
                ty: SigTy::Scalar(ScalarTy::String),
                arity: Arity::One,
                named: false,
            }],
            SigTy::Scalar(ScalarTy::Float),
            LoweringKind::Expr(SmolStr::new("CAST(CAST(%0 AS DECIMAL(38,18)) AS DOUBLE)")),
        ),
        RegistryEntry::new(
            "parse.date",
            vec![
                ParamSpec {
                    name: SmolStr::new("text"),
                    ty: SigTy::Scalar(ScalarTy::String),
                    arity: Arity::One,
                    named: false,
                },
                ParamSpec {
                    name: SmolStr::new("format"),
                    ty: SigTy::Scalar(ScalarTy::String),
                    arity: Arity::One,
                    named: false,
                },
            ],
            SigTy::Scalar(ScalarTy::Date),
            LoweringKind::Expr(SmolStr::new("CAST(strptime(%0, %1) AS DATE)")),
        ),
        RegistryEntry::new(
            "parse.datetime",
            vec![
                ParamSpec {
                    name: SmolStr::new("text"),
                    ty: SigTy::Scalar(ScalarTy::String),
                    arity: Arity::One,
                    named: false,
                },
                ParamSpec {
                    name: SmolStr::new("format"),
                    ty: SigTy::Scalar(ScalarTy::String),
                    arity: Arity::One,
                    named: false,
                },
            ],
            SigTy::Scalar(ScalarTy::DateTime),
            LoweringKind::Expr(SmolStr::new("strptime(%0, %1)")),
        ),
        RegistryEntry::new(
            "math.sum",
            vec![ParamSpec {
                name: SmolStr::new("value"),
                ty: SigTy::Scalar(ScalarTy::Float),
                arity: Arity::One,
                named: false,
            }],
            SigTy::Scalar(ScalarTy::Float),
            LoweringKind::Expr(SmolStr::new("sum(%0)")),
        ),
        RegistryEntry::new(
            "math.avg",
            vec![ParamSpec {
                name: SmolStr::new("value"),
                ty: SigTy::Scalar(ScalarTy::Float),
                arity: Arity::One,
                named: false,
            }],
            SigTy::Scalar(ScalarTy::Float),
            LoweringKind::Expr(SmolStr::new("avg(%0)")),
        ),
        RegistryEntry::new(
            "math.min",
            vec![ParamSpec {
                name: SmolStr::new("value"),
                ty: SigTy::Scalar(ScalarTy::Float),
                arity: Arity::One,
                named: false,
            }],
            SigTy::Scalar(ScalarTy::Float),
            LoweringKind::Expr(SmolStr::new("min(%0)")),
        ),
        RegistryEntry::new(
            "math.max",
            vec![ParamSpec {
                name: SmolStr::new("value"),
                ty: SigTy::Scalar(ScalarTy::Float),
                arity: Arity::One,
                named: false,
            }],
            SigTy::Scalar(ScalarTy::Float),
            LoweringKind::Expr(SmolStr::new("max(%0)")),
        ),
        RegistryEntry::new(
            "math.abs",
            vec![ParamSpec {
                name: SmolStr::new("value"),
                ty: SigTy::Scalar(ScalarTy::Float),
                arity: Arity::One,
                named: false,
            }],
            SigTy::Scalar(ScalarTy::Float),
            LoweringKind::Expr(SmolStr::new("abs(%0)")),
        ),
        RegistryEntry::new(
            "math.round",
            vec![ParamSpec {
                name: SmolStr::new("value"),
                ty: SigTy::Scalar(ScalarTy::Float),
                arity: Arity::One,
                named: false,
            }],
            SigTy::Scalar(ScalarTy::Integer),
            LoweringKind::Expr(SmolStr::new("CAST(round(%0) AS BIGINT)")),
        ),
        RegistryEntry::new(
            "io.csv",
            vec![ParamSpec {
                name: SmolStr::new("uri"),
                ty: SigTy::Scalar(ScalarTy::String),
                arity: Arity::One,
                named: false,
            }],
            SigTy::Rows,
            LoweringKind::Op(PlanOp::Source),
        ),
        RegistryEntry::new(
            "io.json",
            vec![ParamSpec {
                name: SmolStr::new("uri"),
                ty: SigTy::Scalar(ScalarTy::String),
                arity: Arity::One,
                named: false,
            }],
            SigTy::Rows,
            LoweringKind::Op(PlanOp::Source),
        ),
        RegistryEntry::new(
            "io.parquet",
            vec![ParamSpec {
                name: SmolStr::new("uri"),
                ty: SigTy::Scalar(ScalarTy::String),
                arity: Arity::One,
                named: false,
            }],
            SigTy::Rows,
            LoweringKind::Op(PlanOp::Source),
        ),
        RegistryEntry::new(
            "io.rdf",
            vec![ParamSpec {
                name: SmolStr::new("uri"),
                ty: SigTy::Scalar(ScalarTy::String),
                arity: Arity::One,
                named: false,
            }],
            SigTy::Rows,
            LoweringKind::Op(PlanOp::Source),
        ),
    ]
}
