//! @generated by `cargo xtask catalogue` from `catalogue.bnf`. DO NOT EDIT.
//!
//! The rows whose behaviour the compiler can always link: every row that
//! reads DATA. A row that decodes a shape language is emitted into
//! `fossil-descriptors-output` instead — see `xtask::catalogue`.
//!
//! Edit `catalogue.bnf` and re-run `cargo xtask catalogue`.

use super::{Provider, RowReader};

/// The native `DuckDB` readers a [`RowReader::Native`] maps to.
///
/// `fossil-mir` exhaustively maps each to a `SourceFormat`, so a new reader is
/// a compile error until handled — which is the property generating this enum
/// from `catalogue.bnf` is meant to keep, not trade away.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum NativeReader {
    /// `read_csv_auto`.
    CsvAuto,
    /// `read_json_auto`.
    JsonAuto,
    /// `read_parquet`.
    Parquet,
}

impl NativeReader {
    /// The `DuckDB` table function this reader names — the token
    /// `catalogue.bnf` writes after `native`.
    #[must_use]
    pub const fn table_function(self) -> &'static str {
        match self {
            Self::CsvAuto => "read_csv_auto",
            Self::JsonAuto => "read_json_auto",
            Self::Parquet => "read_parquet",
        }
    }
}

/// `io.csv` — reads rows via `read_csv_auto`.
pub static CSV: Provider = Provider {
    name: "csv",
    extensions: &["csv"],
    reads_rows: Some(RowReader::Native(NativeReader::CsvAuto)),
    reads_types: None,
};

/// `io.json` — reads rows via `read_json_auto`.
pub static JSON: Provider = Provider {
    name: "json",
    extensions: &["json"],
    reads_rows: Some(RowReader::Native(NativeReader::JsonAuto)),
    reads_types: None,
};

/// `io.parquet` — reads rows via `read_parquet`.
pub static PARQUET: Provider = Provider {
    name: "parquet",
    extensions: &["parquet"],
    reads_rows: Some(RowReader::Native(NativeReader::Parquet)),
    reads_types: None,
};

/// `io.rdf` — reads rows, materialised outside the reader.
pub static RDF: Provider = Provider {
    name: "rdf",
    extensions: &["ttl", "nt", "n3", "rdf"],
    reads_rows: Some(RowReader::Materialised),
    reads_types: None,
};

/// The rows the compiler can name on its own: everything that reads DATA.
///
/// This is [`crate::system::System::providers`]'s default, and it is a real
/// answer rather than a stub — a host that decodes no shape document still has
/// to recognise `io.csv`. A host that compiles programs installs a superset
/// (`fossil_descriptors_output::PROVIDERS`), and the rows it adds are exactly
/// the ones `catalogue.bnf` gives a `decodes`.
pub static DATA: &[&Provider] = &[&CSV, &JSON, &PARQUET, &RDF];
