//! @generated by `cargo xtask catalogue` from `catalogue.bnf`. DO NOT EDIT.
//!
//! What a `DuckDB` `DESCRIBE` column type means on the lattice — the
//! `duckdb` table of `catalogue.bnf`.
//!
//! Edit `catalogue.bnf` and re-run `cargo xtask catalogue`.

use fossil_base::NativeReader;
use fossil_graph_schema::Primitive;

/// The [`Primitive`] a `DuckDB` column type means: case-blind, the first
/// `duckdb` line of `catalogue.bnf` that matches.
pub fn duckdb_primitive(t: &str) -> Primitive {
    match t.trim().to_ascii_uppercase().as_str() {
        "INTEGER" | "BIGINT" | "INT" | "SMALLINT" | "TINYINT" | "HUGEINT" => Primitive::Integer,
        "DOUBLE" | "FLOAT" | "REAL" => Primitive::Float,
        t if t.starts_with("DECIMAL") => Primitive::Float,
        "BOOLEAN" | "BOOL" => Primitive::Bool,
        "DATE" => Primitive::Date,
        "DATETIME" => Primitive::DateTime,
        t if t.starts_with("TIMESTAMP") => Primitive::DateTime,
        t if t.starts_with("TIME") => Primitive::Time,
        _ => Primitive::String,
    }
}

/// The [`Primitive`] a column one native reader `DESCRIBE`s means: a type
/// its row declares `text` is one the reader inferred from text that the run
/// reads as text, and the rest is [`duckdb_primitive`].
pub fn read_primitive(reader: NativeReader, t: &str) -> Primitive {
    let upper = t.trim().to_ascii_uppercase();
    let text = match reader {
        NativeReader::JsonAuto => {
            upper == "DATE" || upper.starts_with("TIMESTAMP") || upper.starts_with("TIME")
        }
        _ => false,
    };
    if text {
        Primitive::String
    } else {
        duckdb_primitive(t)
    }
}
