[package]
name = "fossil-base"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
description = "Salsa Db trait, System abstraction, and shared input types for the Fossil compiler"

[lints]
workspace = true

[dependencies]
salsa = { workspace = true }
thiserror = { workspace = true }
smol_str = { workspace = true }
