// @generated by `cargo xtask problem` from `crates/fossil-graph-schema/problem.schema.json`. DO NOT EDIT.
//
// The error catalogue — every code fossil can report, its data and its title — projected from
// the JSON Schema of `fossil_graph_schema::Problem`. Change the enum, re-bless the schema
// (`FOSSIL_BLESS=1 cargo test -p fossil-graph-schema --test problem_schema`), and re-run
// `cargo xtask problem`.

/** A code fossil can report: `area/kind`. Stable once released — never reworded, never reused. */
export type Code =
  | 'run/over-budget'
  | 'run/does-not-compile'
  | 'run/destination-uncovered'
  | 'shape/more-than-one-output'
  | 'provider/bare-document-path'
  | 'document/not-registered'
  | 'document/unparseable'
  | 'document/unread'
  | 'provider/unknown'
  | 'provider/wrong-capability'
  | 'provider/wrong-extension'
  | 'source/not-utf8'
  | 'source/unparseable'
  | 'engine/failed'
  | 'write/failed'
  | 'write/unknown-type'
  | 'layout/dangling-endpoint'
  | 'layout/too-large'
  | 'storage/no-credential'
  | 'storage/ambiguous-prefix'
  | 'storage/outside-prefix'
  | 'storage/malformed-credential'
  | 'storage/no-route'
  | 'storage/unreachable'
  | 'storage/no-httpfs'
  | 'storage/host-refused'
  | 'storage/host-silent'
  | 'corpus/unreadable'
  | 'corpus/not-json'
  | 'corpus/unsupported-format'
  | 'corpus/duplicate-table'
  | 'corpus/not-a-location'
  | 'corpus/unknown-table'
  | 'corpus/unknown-column'
  | 'corpus/empty-projection'
  | 'corpus/no-position'
  | 'corpus/filter-type-mismatch'
  | 'api/invalid-argument'
  | 'api/busy'
  | 'api/unknown-handle'
  | 'internal/bug';

/** Every live code, in the catalogue's order. */
export const CODES: readonly Code[] = [
  'run/over-budget',
  'run/does-not-compile',
  'run/destination-uncovered',
  'shape/more-than-one-output',
  'provider/bare-document-path',
  'document/not-registered',
  'document/unparseable',
  'document/unread',
  'provider/unknown',
  'provider/wrong-capability',
  'provider/wrong-extension',
  'source/not-utf8',
  'source/unparseable',
  'engine/failed',
  'write/failed',
  'write/unknown-type',
  'layout/dangling-endpoint',
  'layout/too-large',
  'storage/no-credential',
  'storage/ambiguous-prefix',
  'storage/outside-prefix',
  'storage/malformed-credential',
  'storage/no-route',
  'storage/unreachable',
  'storage/no-httpfs',
  'storage/host-refused',
  'storage/host-silent',
  'corpus/unreadable',
  'corpus/not-json',
  'corpus/unsupported-format',
  'corpus/duplicate-table',
  'corpus/not-a-location',
  'corpus/unknown-table',
  'corpus/unknown-column',
  'corpus/empty-projection',
  'corpus/no-position',
  'corpus/filter-type-mismatch',
  'api/invalid-argument',
  'api/busy',
  'api/unknown-handle',
  'internal/bug',
];

/** What each code carries as `data`. */
export interface ProblemData {
  /**
   * An operator asked for more memory than the run's budget had left. Raised while the graph executes, before any byte of the corpus is written. Sizes are bytes.
   */
  'run/over-budget': {
    budget: number;
    consumer: string;
    requested: number;
    reserved: number;
  };
  /**
   * A run over a program that does not compile. The failure's `related` carries the program's diagnostics.
   */
  'run/does-not-compile': Record<string, never>;
  /**
   * The destination a run writes under is not a prefix any store covers.
   */
  'run/destination-uncovered': {
    destination: string;
  };
  /**
   * A program whose sources declare two different output shapes; one program writes one.
   */
  'shape/more-than-one-output': {
    first: string;
    second: string;
  };
  /**
   * A shape document written as a bare path, with no provider to read it. Also a compile code; the executor reaches it for the output shape.
   */
  'provider/bare-document-path': {
    document: string;
  };
  /**
   * A document the program names that the host never registered.
   */
  'document/not-registered': {
    document: string;
  };
  /**
   * A registered document its provider could not decode.
   */
  'document/unparseable': {
    document: string;
  };
  /**
   * Documents a run needed that the host could not read.
   */
  'document/unread': {
    documents: string[];
  };
  /**
   * A constructor no installed provider answers to.
   */
  'provider/unknown': {
    constructor: string;
  };
  /**
   * A provider asked for something it does not do — types of a row reader.
   */
  'provider/wrong-capability': {
    capability: string;
    constructor: string;
  };
  /**
   * A document whose extension the provider does not read.
   */
  'provider/wrong-extension': {
    constructor: string;
    document: string;
  };
  /**
   * A source's bytes are not UTF-8 text.
   */
  'source/not-utf8': {
    locator: string;
  };
  /**
   * A source's bytes did not parse in the format the program named.
   */
  'source/unparseable': {
    locator: string;
  };
  /**
   * The query engine failed; its own error is the cause.
   */
  'engine/failed': Record<string, never>;
  /**
   * Writing one file of the corpus failed; the store's error is the cause.
   */
  'write/failed': {
    path: string;
  };
  /**
   * A relation naming a vertex type the graph did not materialise.
   */
  'write/unknown-type': {
    relation: string;
    vertex_type: string;
  };
  /**
   * A relation whose rows name vertices that do not exist.
   */
  'layout/dangling-endpoint': {
    before: number;
    dropped: number;
    relation: string;
  };
  /**
   * More vertices than a `u32` `dense_id` can number.
   */
  'layout/too-large': {
    vertices: number;
  };
  /**
   * The host vended no credential for a scope.
   */
  'storage/no-credential': {
    access: string;
    scope: string;
  };
  /**
   * A scope whose credentials cover more than the one prefix a reader needs.
   */
  'storage/ambiguous-prefix': {
    count: number;
    scope: string;
  };
  /**
   * A locator outside every prefix a credential was vended for.
   */
  'storage/outside-prefix': {
    locator: string;
    prefix: string;
  };
  /**
   * A vended credential fossil cannot read: a missing or malformed key, or a prefix that is not a directory.
   */
  'storage/malformed-credential': {
    key: string;
    prefix: string;
    reason: string;
  };
  /**
   * A locator no kind of store fossil reads can route.
   */
  'storage/no-route': {
    locator: string;
  };
  /**
   * A store answered with an error; the store's error is the cause.
   */
  'storage/unreachable': {
    locator: string;
  };
  /**
   * The engine a host handed over cannot read remote storage.
   */
  'storage/no-httpfs': Record<string, never>;
  /**
   * The host refused a request for credentials; its rejection is the cause.
   */
  'storage/host-refused': {
    scope: string;
  };
  /**
   * The host did not answer a request for credentials or connections within the deadline fossil holds every host wait to; `after` is that deadline, in milliseconds.
   */
  'storage/host-silent': {
    after: number;
    scope: string;
  };
  /**
   * A corpus whose manifest could not be read; the reader's error is the cause.
   */
  'corpus/unreadable': {
    path: string;
  };
  /**
   * A manifest that is not JSON.
   */
  'corpus/not-json': {
    path: string;
  };
  /**
   * A manifest declaring a format this reader does not read.
   */
  'corpus/unsupported-format': {
    format: string;
    path: string;
  };
  /**
   * A manifest declaring one table twice.
   */
  'corpus/duplicate-table': {
    table: string;
  };
  /**
   * A corpus location carrying a query or a fragment. A corpus is a prefix and every file is named under it; a query string — a signature among them — addresses one object and does not survive the join. Signed storage is reached by opening a job under the host that vends it.
   */
  'corpus/not-a-location': {
    location: string;
  };
  /**
   * A table the corpus does not have.
   */
  'corpus/unknown-table': {
    table: string;
    tables: string[];
  };
  /**
   * A column a table does not declare.
   */
  'corpus/unknown-column': {
    column: string;
    columns: string[];
    table: string;
  };
  /**
   * A projection that selects no column.
   */
  'corpus/empty-projection': {
    table: string;
  };
  /**
   * A spatial filter over a table that declares no position.
   */
  'corpus/no-position': {
    table: string;
  };
  /**
   * A filter comparing a column with a value of another type.
   */
  'corpus/filter-type-mismatch': {
    column: string;
    holds: string;
    value: string;
  };
  /**
   * An argument a caller passed that is not what the call takes.
   */
  'api/invalid-argument': {
    argument: string;
    expected: string;
  };
  /**
   * A call made while another call on the same object is still running.
   */
  'api/busy': {
    call: string;
  };
  /**
   * A handle that names nothing — dropped, or never issued.
   */
  'api/unknown-handle': Record<string, never>;
  /**
   * Fossil's own fault, not the caller's. Nobody branches on it; a host shows it and reports it.
   */
  'internal/bug': {
    what: string;
  };
}

/** Each code's title — fixed per code (RFC 9457 `title`); may be reworded in any release. */
export const TITLES: { readonly [C in Code]: string } = {
  'run/over-budget': 'The run needs more memory than its budget',
  'run/does-not-compile': 'The program does not compile',
  'run/destination-uncovered': 'No store covers the destination',
  'shape/more-than-one-output': 'More than one output shape',
  'provider/bare-document-path': 'A document path with no provider',
  'document/not-registered': 'A document is not registered',
  'document/unparseable': 'A document does not parse',
  'document/unread': 'Documents could not be read',
  'provider/unknown': 'Not a provider this host installs',
  'provider/wrong-capability': 'The provider cannot do this',
  'provider/wrong-extension': 'The provider does not read this extension',
  'source/not-utf8': 'A source is not UTF-8',
  'source/unparseable': 'A source does not parse',
  'engine/failed': 'The query engine failed',
  'write/failed': 'A corpus file could not be written',
  'write/unknown-type': 'A relation names a missing vertex type',
  'layout/dangling-endpoint': 'A relation names missing vertices',
  'layout/too-large': 'The graph has too many vertices',
  'storage/no-credential': 'No credential was vended',
  'storage/ambiguous-prefix': 'More than one prefix was vended',
  'storage/outside-prefix': 'Outside the vended prefix',
  'storage/malformed-credential': 'A credential is malformed',
  'storage/no-route': 'No store routes this locator',
  'storage/unreachable': 'A store could not be reached',
  'storage/no-httpfs': 'The engine cannot read remote storage',
  'storage/host-refused': 'The host refused',
  'storage/host-silent': 'The host did not answer',
  'corpus/unreadable': 'The corpus could not be read',
  'corpus/not-json': 'The manifest is not JSON',
  'corpus/unsupported-format': 'The corpus format is not supported',
  'corpus/duplicate-table': 'A table is declared twice',
  'corpus/not-a-location': 'Not a corpus location',
  'corpus/unknown-table': 'Not a table of this corpus',
  'corpus/unknown-column': 'Not a column of this table',
  'corpus/empty-projection': 'The projection selects nothing',
  'corpus/no-position': 'The table has no position',
  'corpus/filter-type-mismatch': 'The filter compares different types',
  'api/invalid-argument': 'An argument is invalid',
  'api/busy': 'Another call is running',
  'api/unknown-handle': 'The handle names nothing',
  'internal/bug': 'An internal error',
};
