// @generated by `crates/xtask/tests/wire.rs` from the types that cross `wasm-bindgen` and the `Host` contract. DO NOT EDIT:
// `UPDATE_EXPECT=1 cargo test -p xtask --test wire` rewrites it.

/**
 * What a credential was vended for.
 */
export type Access = 'read' | 'write';

/**
 * One entry of `CheckRow::related` — a place, and what is there.
 */
export interface CheckRelated {
  message: string;
  range: Range;
  uri: string;
}

/**
 * One diagnostic row in the `WasmWorkspace::check` return array: the workspace's own shape, not the
 * LSP wire's (`lsp_types::Diagnostic`).
 *
 * `check()` is one flat array across every open file, so each row carries the `uri` the host opened
 * its buffer under. Everything else is projected from the rendering an editor is shown, so the two
 * cannot disagree. `CheckRow` in `@fossil-lang/types` is this, with `data` typed by `code`.
 */
export interface CheckRowBase {
  /**
   * The problem's code — `area/kind`, what a host branches on.
   */
  code: string;
  /**
   * The problem's `data`: the values its message interpolates, typed per code by `ProblemData` in
   * `@fossil-lang/types`.
   */
  data: unknown;
  /**
   * A replacement for a misspelt name — `Diagnostic::did_you_mean`, its span as a UTF-16 range in
   * the diagnostic's own file.
   */
  didYouMean?: Replacement;
  /**
   * What to do about it, in prose — `Diagnostic::help`.
   */
  help?: string;
  /**
   * The problem rendered, for a person. Nothing parses it.
   */
  message: string;
  range: Range;
  /**
   * The other places this one diagnostic points at — LSP's `relatedInformation`, in this array's
   * own shape.
   *
   * Empty for nearly every diagnostic. Non-empty when the mistake needs a second underline: two
   * mappings minting two identities for one type, the binding a row came from, and the line of the
   * `.shex` a violated constraint is declared on — which is in ANOTHER FILE, and is why each
   * entry carries its own key.
   *
   * `uri` here is the registry key verbatim, matching `Self::uri`, and NOT put through
   * `fossil_ide::file_uri`: a caller filtering this array by the path it opened a file under has to
   * find the same string in both fields. The LSP wire does convert, because LSP will not accept
   * anything else.
   */
  related?: CheckRelated[];
  severity: 1 | 2 | 3 | 4;
  /**
   * Fossil source that repairs it — `Diagnostic::suggestion_source`.
   */
  suggestion?: string;
  /**
   * Fixed per code — `fossil_base::Problem::title`.
   */
  title: string;
  uri: string;
}

/**
 * One completion candidate.
 *
 * # `kind` is a NAME, and that is the whole reason this type exists
 *
 * LSP spells `CompletionItemKind` as an integer, and the predecessor of
 * `packages/codemirror-fossil` is what happens when a number crosses this boundary: it hard-copied
 * the lexer's discriminants into a TS enum and was wrong in nine places by the time it was deleted.
 * The numbers here are the LSP spec's rather than fossil's, so they are not going to be renumbered
 * — but the table that reads them would still live in TypeScript, where nothing can check it.
 * `kind_name` puts it in Rust, where `every_lsp_kind_has_a_name` does.
 *
 * The name is the LSP constant, lowercased (`FUNCTION` → `"function"`, `ENUM_MEMBER` →
 * `"enum_member"`). Mapping it onto whatever vocabulary an editor draws icons from is that editor's
 * layer's job.
 */
export interface CompletionRow {
  /**
   * The signature, the shape property's IRI, the source field's type — whatever `fossil-ide`
   * wrote beside the label. `""` when it wrote none.
   */
  detail: string;
  /**
   * The text a pick writes, which is the label's one spelling: the label itself, or `"Person.id"`
   * for a column whose name is not an identifier (`fossil_syntax::name`). Never empty and never
   * absent.
   */
  insert: string;
  /**
   * The LSP kind, by name; `""` when the item carries none.
   */
  kind: string;
  label: string;
}

/**
 * One place a definition is.
 *
 * `uri` is the registry key VERBATIM — the path the host opened the buffer under, which in a
 * browser is usually a bare name like `hello.shex` and not a URI. Same choice as
 * `crate::CheckRow::uri` and for the same reason: a caller matching this against the buffer it
 * opened has to find the same string it passed in. The LSP wire converts, because LSP will not
 * accept anything else; this surface has no wire to satisfy.
 *
 * A target in ANOTHER file is the ordinary case rather than the exception — two of the three
 * positions goto-def recognises resolve into the shape document — so a host with one editor pane
 * still has to read `uri` before it moves a cursor.
 */
export interface DefinitionRow {
  range: Range;
  uri: string;
}

/**
 * How many rows of one relation's input did not become an edge.
 *
 * `execute_edge` resolves both endpoints against the vertex tables with an inner join, so a row
 * naming a subject no vertex carries is discarded. **That is intended and it stays** — a corpus
 * cannot hold an edge to a vertex that is not there — and it is counted rather than silent.
 *
 * # Why the count is here and not in `fossil.json`
 *
 * No reader can verify it: `record_count` earns its place in the manifest by being answerable to
 * the Parquet, and a dropped count is about rows that are not there and never were. And a
 * third-party writer has no such number — it performs no join — so a manifest field for it
 * would make a conforming corpus impossible to write without a fact only fossil's pipeline has.
 */
export interface EdgeDrops {
  /**
   * Rows of its input that resolved no endpoint pair.
   */
  dropped: number;
  /**
   * The edge table's name in `fossil.json`, `<Src>_<label>_<Dst>`.
   */
  table: string;
}

/**
 * What a host does with a credential: the statements that put it in the engine and take it out, and
 * when it stops working.
 */
export interface GrantPlan {
  /**
   * When it stops working, in milliseconds since 1970; absent when the host did not say.
   */
  expiresAtMs?: number;
  /**
   * The statement that installs it; absent for a store the engine is lent file by file.
   */
  install?: string;
  /**
   * The prefix the credential covers.
   */
  prefix: string;
  /**
   * The statement that takes `install` back.
   */
  uninstall?: string;
}

/**
 * What is under the cursor, rendered — the payload of `textDocument/hover` with the LSP envelope
 * taken off.
 *
 * `markdown` is `fossil_ide::hover_bidirectional`'s: a ```` ```fossil ```` fence, the source-side
 * type and where it came from, and — when the program names an output document that resolves —
 * a second block with the type the shape demands of that predicate. `range` is UTF-16, because a JS
 * host counts in UTF-16 and LSP does too.
 */
export interface HoverRow {
  markdown: string;
  range: Range;
}

/**
 * One column from a host-introspected source.
 */
export interface InferredColumn {
  /**
   * Column name as introspected (`DuckDB` `column_name`).
   */
  name: string;
  /**
   * The column's place in the lattice — the same enum the checker types against, so a host sends
   * `"integer"`, not a name the consumer has to look up. A value outside the lattice fails here, at
   * deserialisation, naming itself; it does not become a `String` column and a diagnostic three
   * crates away.
   */
  primitive: Primitive;
}

/**
 * A descriptor inferred from a runtime file introspection.
 *
 * Identified by the source **URI**, which is what the descriptor is about: a binding name is a name
 * for the *program*'s convenience, and two of them can point at one file.
 */
export interface InferredDescriptor {
  /**
   * Ordered columns; the order is the source's own and is significant.
   */
  columns: InferredColumn[];
  /**
   * Opaque token identifying the state of the source this was read from. The cache compares it;
   * nothing interprets it. `fossil-introspect` writes `mtime` + size, a host that has a strong
   * `ETag` or a content digest writes that instead, and a host that cannot cheaply tell writes `""`
   * — which `crate::DescriptorCache::is_fresh` reads as "never fresh", so that source is
   * re-introspected every time. It is NOT a hash of the bytes, and deliberately: hashing means
   * reading the whole source to decide whether the source needs reading, which makes the cache cost
   * more than the `DESCRIBE` it saves. `mtime` + size is two fields of one `stat`. Its one
   * dangerous failure — saying "unchanged" when it changed — needs a file restored with the
   * same `mtime` AND the same size, which is what pairing the two narrows.
   */
  freshness_token: string;
  /**
   * The source URI exactly as written in the program — the string inside
   * `io.csv("examples/users.csv")`. NOT the resolved locator: the host resolves (`@conn` aliases, a
   * program-relative path, a signed URL) in order to *read* the source, but the checker only ever
   * sees what the program says, so that is the only string both ends can agree on.
   */
  uri: string;
}

/**
 * What SQL calls a locator under a credential.
 */
export interface LocatorName {
  /**
   * The URL the engine lends `name` to; absent when the name is readable as it is.
   */
  lend?: string;
  /**
   * The name a statement reads.
   */
  name: string;
}

/**
 * A document a program names and the workspace does not hold yet —
 * `fossil_hir::documents::MissingDocument` in the shape it crosses to JS.
 */
export interface MissingDocument {
  /**
   * The connection the locator lies under, when the program wrote `@name/…`.
   */
  connection?: string;
  /**
   * The registry key: what the program wrote, independent of any connection.
   */
  key: string;
  /**
   * Where to read it: the key expanded through the connection map.
   */
  locator: string;
}

/**
 * Zero-based line and UTF-16 column — LSP's `Position`.
 */
export interface Position {
  character: number;
  line: number;
}

/**
 * The canonical datatype lattice — format-neutral, and **the same enum the type system checks
 * against** (`TyKind::Primitive`). It lives in this crate because the schema, the checker and the
 * descriptors all speak it, and a lattice that crosses a crate boundary as a string is a lattice
 * with no single definition.
 *
 * Materializers map it to their own vocabulary (`fossil.json` `string/int64/double/…`,
 * `DataFusion` scalars, `DuckDB` column types) next to the materializer; only the xsd direction
 * lives here, because xsd is the RDF border every side reads.
 */
export type Primitive = 'string' | 'integer' | 'float' | 'bool' | 'date' | 'date_time' | 'time' | 'g_year' | 'any_uri';

/**
 * A data source a program reads, as fossil resolved it — `ProgramSource` in `@fossil-lang/types`.
 */
export interface ProgramSource {
  /**
   * The binding the source is read into (`users` in `users := io.csv(…)`).
   */
  binding: string;
  /**
   * The connection the locator lies under, when it was written `@name/…`.
   */
  connection?: string;
  /**
   * The catalogue row the constructor names (`csv`), which chooses the reader.
   */
  format: string;
  /**
   * The URI as the program wrote it — what an inferred descriptor is keyed by.
   */
  key: string;
  /**
   * `key` through `fossil_locator::SourceAnchor`: what a host signs and reads.
   */
  locator: string;
  /**
   * The reader option the binding wrote (`delimiter = "|"`), verbatim.
   */
  option?: string;
}

/**
 * One data-source provider fossil exposes: its short name, the file extensions it reads, and how it
 * can be used. A host lists these so its UI can offer the constructors and filter files by
 * extension.
 */
export interface ProviderInfo {
  /**
   * File extensions this provider reads (no leading dot).
   */
  extensions: string[];
  /**
   * Whether the provider defines a type, loads data, or both.
   */
  kind: ProviderKind;
  /**
   * Short provider name (e.g. `csv`, `json`, `parquet`).
   */
  name: string;
}

/**
 * What a provider can appear as in a program.
 */
export type ProviderKind = 'schema' | 'data' | 'both';

/**
 * Inclusive `start`, exclusive `end` — LSP's `Range`.
 */
export interface Range {
  end: Position;
  start: Position;
}

/**
 * The position a reference plays in an `io.*` source constructor.
 */
export type RefRole = 'data' | 'schema';

/**
 * Replace the text at `range` with `replacement`.
 */
export interface Replacement {
  range: Range;
  replacement: string;
}

/**
 * Where a run wrote, and what the write discarded.
 */
export interface RunReport {
  /**
   * The prefix the corpus was written under, `fossil.json` at its root.
   */
  dest: string;
  /**
   * One entry per relation, in the order `fossil.json` lists its edge tables.
   */
  dropped: EdgeDrops[];
}

/**
 * What a credential is asked for: a connection's prefix, or a job's dataset.
 */
export type Scope = {
  connection: string;
} | {
  job: string;
};

/**
 * One classified span of the program — `textDocument/semanticTokens/full` as absolute rows rather
 * than the LSP delta stream.
 *
 * `kind` and `modifiers` are the legend's NAMES (`"type"`, `"declaration"`), for the reason
 * `CompletionRow::kind` is one: the number is an index into a table, and the table belongs on the
 * side that can check it. `range` is UTF-16, like every other range on this surface, and unlike the
 * LSP stream it may cross a line — a multi-line string is one row.
 *
 * The rows are in source order and never overlap; a connection reference is carved out of its
 * string literal, so `"@warehouse/x.csv"` is three rows.
 */
export interface SemanticTokenRow {
  kind: string;
  /**
   * Empty when the span carries none — never absent.
   */
  modifiers: string[];
  range: Range;
}

/**
 * One external reference a program makes. `connection` is the `@conn` alias the reference targets
 * (`Some("cpi")` for `@cpi/graph.ttl`), or `None` for a direct URL / local path. `path` is the
 * remainder after the alias (or the whole locator when there is no alias). This is the program's
 * TYPED lineage — a host derives a job's connection set from the distinct `connection`s, never
 * from a regex over the script text.
 */
export interface SourceRefInfo {
  /**
   * The `@conn` alias this reference targets; absent for a direct URL/path.
   */
  connection?: string;
  /**
   * The path within the connection, or the whole locator when unaliased.
   */
  path: string;
  /**
   * Where this reference appears in the source constructor.
   */
  role: RefRole;
}

/**
 * A storage credential scoped to one prefix — Iceberg REST's `StorageCredential`, verbatim on the
 * wire.
 *
 * `config` carries Iceberg's keys: `s3.access-key-id`, `s3.secret-access-key`, `s3.session-token`,
 * `s3.endpoint`, `s3.path-style-access`, `client.region`, `s3.session-token-expires-at-ms`; or
 * `adls.sas-token.<host>` and `adls.sas-token-expires-at-ms.<host>`, `<host>` being the prefix's
 * `<account>.dfs.core.windows.net`.
 */
export interface StorageCredential {
  /**
   * Iceberg's keys, as above.
   */
  config: Record<string, string>;
  /**
   * `s3://bucket/path/` or `abfss://container@account.dfs.core.windows.net/path/`.
   */
  prefix: string;
}

/**
 * One token, serialised as its variant name — the name a highlighter keys on.
 */
export type Token = 'Whitespace' | 'Newline' | 'Comment' | 'KwFrom' | 'KwAnd' | 'KwOr' | 'KwNot' | 'AtAttr' | 'True' | 'False' | 'Null' | 'Float' | 'Integer' | 'Ident' | 'String' | 'Define' | 'Eq' | 'Neq' | 'Le' | 'Ge' | 'Assign' | 'Dot' | 'Comma' | 'LParen' | 'RParen' | 'LBrace' | 'RBrace' | 'Lt' | 'Gt' | 'Plus' | 'Minus' | 'Star' | 'Slash' | 'Percent' | 'Question' | 'Colon';

/**
 * One token: its name, and where it is in UTF-16 code units.
 */
export interface TokenRow {
  /**
   * Exclusive end, in UTF-16 code units.
   */
  end: number;
  kind: Token;
  /**
   * Inclusive start, in UTF-16 code units.
   */
  start: number;
}

/** `fossil_storage::HOST_MS`. */
export const HOST_MS = 30000;

/** `fossil_storage::RENEW_BEFORE_MS`. */
export const RENEW_BEFORE_MS = 300000;
