// @generated by `crates/xtask/tests/wire.rs` from `fossil_sinks::manifest::Manifest`. DO NOT EDIT:
// `UPDATE_EXPECT=1 cargo test -p xtask --test wire` rewrites it.

/**
 * What a column IS — never what a reader does with it.
 *
 * A reader that used to carry a list now names the roles it means. It is data in `fossil.json` too:
 * a writer column's `role` in its table's `properties`, spelled as the variant in lowercase.
 */
export type ColumnRole = 'address' | 'identity' | 'endpoint';

/**
 * One relation's table.
 */
export interface EdgeTable {
  /**
   * The column holding the destination vertex's `dense_id`, and its table.
   */
  destination: Endpoint;
  /**
   * The relation's IRI, when the program's shape document gives one.
   */
  iri?: string;
  /**
   * The relation's label, e.g. `placedBy`.
   */
  label: string;
  /**
   * `<Src>_<label>_<Dst>`, unique: the label repeats across relations.
   */
  name: string;
  /**
   * The table's Parquet file, relative to the corpus root.
   */
  path: string;
  /**
   * Every column of the file, in file order.
   */
  properties: Property[];
  /**
   * Rows in the file.
   */
  record_count: number;
  /**
   * The column holding the source vertex's `dense_id`, and its table.
   */
  source: Endpoint;
}

/**
 * One end of a relation.
 */
export interface Endpoint {
  /**
   * The edge table's column.
   */
  key: string;
  /**
   * The vertex table whose `key` it holds.
   */
  references: string;
}

/**
 * The whole of `fossil.json`.
 */
export interface Manifest {
  /**
   * One per relation, in the order the compiled schema lists them.
   */
  edge_tables: EdgeTable[];
  /**
   * The format the corpus is written in.
   */
  format: 'fossil/1';
  /**
   * One per vertex type, in the order the compiled schema lists them.
   */
  vertex_tables: VertexTable[];
}

/**
 * One column.
 */
export interface Property {
  /**
   * The predicate IRI the program mapped it from, when there is one.
   */
  iri?: string;
  /**
   * The column name, as in the Parquet schema.
   */
  name: string;
  /**
   * Whether a row may hold no value. Absent is `false`.
   */
  nullable?: boolean;
  /**
   * What the column IS, for a column the writer emits — `corpus.bnf`'s role, so a reader names
   * the roles it means rather than the names it remembers. Absent on a column of the program's.
   */
  role?: ColumnRole;
  /**
   * Its type, in the spelling `data_type_name` writes.
   */
  type: string;
}

/**
 * One vertex type's table.
 */
export interface VertexTable {
  /**
   * The identity column: `subject`, unique within the table.
   */
  identity: string;
  /**
   * The type's IRI, when the program's shape document gives one.
   */
  iri?: string;
  /**
   * The key column: `dense_id`, global and gapless across every vertex table, and one contiguous
   * range of it per table, in manifest order.
   */
  key: string;
  /**
   * The type's label: the name of the table and its PGQ label.
   */
  name: string;
  /**
   * The table's Parquet file, relative to the corpus root.
   */
  path: string;
  /**
   * Every column of the file, in file order.
   */
  properties: Property[];
  /**
   * Rows in the file.
   */
  record_count: number;
}
