// @generated by `cargo xtask catalogue` from `catalogue.bnf`. DO NOT EDIT.
//
// Every `io.` constructor that reads DATA. This is the wire vocabulary of
// `FossilExecutor.sources()` and `SourceInput.format`: the string IS the
// catalogue row's name, and `fossil-df-wasm` reads it back with
// `source_row`. Unlike the introspect list, `io.rdf` is here — the host
// fetches its bytes like any other source; only the staging differs.
//
// Edit `catalogue.bnf` and re-run `cargo xtask catalogue`.

/** Every `io.` constructor that reads data, in catalogue order. */
export const DATA_ROWS = ["csv", "json", "parquet", "rdf"] as const;

/** The fetch strategy for a source — how the host must stage its bytes. */
export type DataRow = (typeof DATA_ROWS)[number];
