// @generated by `cargo xtask catalogue` from `catalogue.bnf`. DO NOT EDIT.
//
// Every `io.` constructor that reads DATA. This is the wire vocabulary of
// `FossilExecutor.sources()`: the string IS the catalogue row's name.
// Unlike the introspect list, `io.rdf` is here — the executor reads its
// bytes through the same storage as any other source; only the decoding
// differs.
//
// Edit `catalogue.bnf` and re-run `cargo xtask catalogue`.

/** Every `io.` constructor that reads data, in catalogue order. */
export const DATA_ROWS = ["csv", "json", "parquet", "rdf"] as const;

/** The fetch strategy for a source — how the host must stage its bytes. */
export type DataRow = (typeof DATA_ROWS)[number];
