[package]
name = "fossil-syntax"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
description = "Lossless concrete syntax tree for the Fossil DSL (rowan + logos)"

[lints]
workspace = true

[dependencies]
fossil-base = { path = "../fossil-base" }
salsa = { workspace = true }
rowan = { workspace = true }
logos = { workspace = true }
text-size = { workspace = true }
smol_str = { workspace = true }

[dev-dependencies]
expect-test = { workspace = true }
