//! @generated by `cargo xtask catalogue` from `catalogue.bnf`. DO NOT EDIT.
//!
//! The rows that read TYPES, and [`PROVIDERS`] — every row in
//! `catalogue.bnf`, which is what a COMPILING host installs.
//!
//! Each `decodes` token below is a Rust path, so the compiler resolves it.
//! That is what the parity test this replaces said it could not prove: a `fn`
//! pointer has no name at run time, and a row could declare a capability whose
//! function nobody had written.
//!
//! Edit `catalogue.bnf` and re-run `cargo xtask catalogue`.

use fossil_base::Provider;
use fossil_base::providers::{CSV, JSON, PARQUET, RDF};

use super::{decode_shacl, decode_shex};

/// `io.shex` — reads types via `decode_shex`.
pub static SHEX: Provider = Provider {
    name: "shex",
    extensions: &["shex", "shexj", "shexc"],
    reads_rows: None,
    reads_types: Some(decode_shex),
};

/// `io.shacl` — reads types via `decode_shacl`.
pub static SHACL: Provider = Provider {
    name: "shacl",
    extensions: &["ttl", "shacl"],
    reads_rows: None,
    reads_types: Some(decode_shacl),
};

/// **The registry a compiling host installs**: every row `catalogue.bnf`
/// declares, in file order.
///
/// A host that returns this from `System::providers` recognises every `io.*`
/// the language has. The default (`fossil_base::providers::DATA`) is the data
/// rows alone, which is correct for a host that runs a plan somebody else
/// compiled and wrong for the host the plan comes from.
pub static PROVIDERS: &[&Provider] = &[&CSV, &JSON, &PARQUET, &RDF, &SHEX, &SHACL];
